### ISSUE TITLE
Feature Request: Ability to collapse/hide filters?

### ISSUE THREAD

**Issue by Pentaphon** [openscopeproject/TrguiNG#10]
Say I don't want to see the status filters all the time and it takes too much space, can we have the ability to collapse the filter by say clicking on the title? Or an arrow that clicked, points right or down to show whether the filter has been collapsed or open?

**Comment by qu1ck** [comment]
Implemented in [v0.3.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v0.3.0). Right click in filters section to reorder/hide them like the columns in table header.

**Comment by Pentaphon** [comment]
Oh wow, ok you are fast! I didn't see that 0.3.0 just came out! Closing and thanks!
