### ISSUE TITLE
Crash clears configurations

### ISSUE THREAD

**Issue by Willian-Zhang** [openscopeproject/TrguiNG#102]
An app crash causes server configurations to be lost.

btw the crash was by clicking "browse..."

Platform
Mac aarch 

version: 0.9.0

**Comment by qu1ck** [comment]
Ugh, this is likely https://github.com/tauri-apps/tauri/issues/7566 again.
I'll fix this asap but as a workaround, put anything in the path field, even just `/` is enough, browse button should work then.

**Comment by qu1ck** [comment]
Also to permanently save your server settings quit the app normally once after changing config.

**Comment by qu1ck** [comment]
Fixed in [v1.0.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v1.0.0)
