### ISSUE TITLE
WebUI: Put speed in front of title on tab

### ISSUE THREAD

**Issue by Pentaphon** [openscopeproject/TrguiNG#106]
Instead of:

Favicon TrguiNG [Speeds]
can we have 
Favicon [Speeds] TrguiNG instead?
This helps on tabs made smaller by having numerous tabs on smaller screens.

**Comment by qu1ck** [comment]
Implemented in [v1.0.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v1.0.0)
