### ISSUE TITLE
Webui/windows - Unable to change order of the columns 

### ISSUE THREAD

**Issue by Beersteddy** [openscopeproject/TrguiNG#107]
Webui 0.10
Windows app 0.10

Self explanatory pretty much
Order of the columns can't be changed.
Unsure if is a bug or not implemented just yet

![image](https://github.com/openscopeproject/TrguiNG/assets/91010735/32a3a4f4-3db9-4ff2-96ab-6ebccd46c151)

**Comment by qu1ck** [comment]
Right click the table header, drag and drop the columns by the handle on the right.

**Comment by qu1ck** [comment]
![image](https://github.com/openscopeproject/TrguiNG/assets/3622532/8444b3f7-99f4-4702-a19a-3f61f7e9db8c)

**Comment by Beersteddy** [comment]
Most say this is very unusual to rearrange columns. Usually just dragging them works fine.
As long as is there - the problem is fixed.

Thanks, and I really appreciate what you doing by bringing a new life to Transgui which was crashing very often.
