### ISSUE TITLE
Dark and Light Modes should have seperate text and background color configurations

### ISSUE THREAD

**Issue by Pentaphon** [openscopeproject/TrguiNG#108]
Let's say you install TrguiNG for the first time and you switch to dark mode but you want the dark mode to be darker, so you switch the background color to something darker. When you go back to light mode for when you feel like using light mode, the chosen background is still being preserved and the client results in a messy mix of dark and light colors. We need separate text and background color configs for both light and dark mode so when you switch between them, they stay the same regardless of how you changed the text and background color setting in each mode. 

![color](https://github.com/openscopeproject/TrguiNG/assets/49374058/0858a5ae-99e1-4d2b-bb26-212c5ec9d153)

**Comment by qu1ck** [comment]
Fixed in [v1.0.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v1.0.0)
