### ISSUE TITLE
Default trackers list should be empty?

### ISSUE THREAD

**Issue by Pentaphon** [openscopeproject/TrguiNG#109]
Currently seeing this and I didn't add them. 

![def](https://github.com/openscopeproject/TrguiNG/assets/49374058/93e9c077-2ae3-419f-a3f3-b18c0e342e32)

**Comment by qu1ck** [comment]
This list is preconfigured default. It's there to help prefill torrent creation form with popular trackers and to add to existing torrents if you want.

**Comment by lunik1** [comment]
This list seems to override the `default-trackers` setting for the transmission daemon, is that intended?

**Comment by qu1ck** [comment]
It is not intended but I also don't see this list interacting with transmission's own default tracker list in any way. 

Can you add more details about the behavior you observe, what you mean by overriding?

**Comment by lunik1** [comment]
I would have expected this list to match the `default-trackers` list (which I have set), but instead it stays as this default.

**Comment by qu1ck** [comment]
This affects only the interface itself, just a quick way to insert trackers into torrent at creation time (for standalone app) or for seeding.

It does not touch transmission's setting of the same name which is why it's in the interface section.
