### ISSUE TITLE
Some issues with 0.3.0

### ISSUE THREAD

**Issue by mahkitah** [openscopeproject/TrguiNG#11]
Thanks for releasing 0.3.0. With the tracker filter it has already made it to the top of my Transmission remote GUI's list.

Some issues I found:
-Ctrl-A behaviour:
Ctrl-A will select everything in the bottom pane, and that selection will remain when clicking on a different torrent.
Expected behaviour: Select all torrents in the main table.

-Hiding a filter section keeps the filter active:
Let's say you selected tracker A in the tracker section, when you then hide the tracker section you still only see torrents from tracker A.
Expected: hiding a filter section should disable the filter.

-Seeds and Peers columns only show 'connected' seeds/peers:
Most torrent clients will show 2 numbers per column: connected and total
Connected Seeds/Peers is 0 most of the time.

-Ratio column is left aligned:
Other 'number based' columns are right aligned.
It's difficult to see column separation when there's a right-aligned column to the left af the ratio column.

**Comment by qu1ck** [comment]
Implemented/fixed in [v0.4.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v0.4.0).
