### ISSUE TITLE
Background and text color selector gets cut off at bottom by taskbar on small screens

### ISSUE THREAD

**Issue by Pentaphon** [openscopeproject/TrguiNG#110]
This is on a 1366x768 screen. The selector should be entirely visible but gets cut off at the bottom by the Windows taskbar and bottom of the browser when maximized. 

![cut](https://github.com/openscopeproject/TrguiNG/assets/49374058/86b52dd7-b604-4a3b-89da-d1f493b9778c)

**Comment by qu1ck** [comment]
Fixed in [v1.0.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v1.0.0)
