### ISSUE TITLE
Allow user to configure the selection color? (Bold Blue by default) 

### ISSUE THREAD

**Issue by Pentaphon** [openscopeproject/TrguiNG#111]
I would like to make the selection color a much lighter blue. Can you make the selection color configurable like the text and background? Preferably with 2 different configs for both light and dark mode as requested in https://github.com/openscopeproject/TrguiNG/issues/108 ?

![select](https://github.com/openscopeproject/TrguiNG/assets/49374058/6648ae68-4d5b-4fb3-bfa0-c53c0d45e1cc)

**Comment by qu1ck** [comment]
I don't plan to add color config for every widget, it's impractical and will be absolute pain to maintain.
If you are willing to compile yourself and maintain your patches then you can change this: https://github.com/openscopeproject/TrguiNG/blob/6ab6567e654b4217575b6a51197dea0013777e20/src/css/custom.css#L87
