### ISSUE TITLE
Force-Verify-Torrent - new function added to transmissionRPC

### ISSUE THREAD

**Issue by Beersteddy** [openscopeproject/TrguiNG#112]
Can we have this functionality added to TrguiNG?

More info
https://github.com/search?q=repo%3Atransmission%2Ftransmission%20tr_torrentVerifyForce&type=code

https://github.com/transmission/transmission/issues/6204

https://github.com/transmission/transmission/pull/5981

**Comment by qu1ck** [comment]
Great, I needed this feature a few times. I'll wait until it's stabilized but it will definitely be added in TrguiNG.

**Comment by Beersteddy** [comment]
> Great, I needed this feature a few times. I'll wait until it's stabilized but it will definitely be added in TrguiNG.

Ha. Gonna be honest. I would kill for it right now. Have a hundreds of torrents to force-recheck right now

**Comment by qu1ck** [comment]
If you need it right now you can change these 2 instances with "torrent-verify-force" and compile
https://github.com/search?q=repo%3Aopenscopeproject%2FTrguiNG%20torrent-verify&type=code.
Note, you will need to compile your transmission server from master too.

**Comment by Beersteddy** [comment]
> If you need it right now you can change these 2 instances with "torrent-verify-force" and compile https://github.com/search?q=repo%3Aopenscopeproject%2FTrguiNG%20torrent-verify&type=code. Note, you will need to compile your transmission server from master too.

Thanks. But I'm just a user, maybe a tester, definitely not a dev. 
No idea how to do it

**Comment by qu1ck** [comment]
This is now fixed in transmission without api change, see https://github.com/transmission/transmission/pull/6277

So TrguiNG (and any other UI) will get this feature for free when you transmission 4.1 is released.
