### ISSUE TITLE
Russian characters in filenames

### ISSUE THREAD

**Issue by sHAsHiLx** [openscopeproject/TrguiNG#114]
There is problems with display and translating russian characters. On this screenshot you cant see it with ?
![изображение](https://github.com/openscopeproject/TrguiNG/assets/20460472/bc6df455-abf1-4134-bae9-2738af39d226)
and of course if double click on it - it errors with 
![изображение](https://github.com/openscopeproject/TrguiNG/assets/20460472/76bbd7cc-c972-497c-9e0b-946b13cb6333)
If I go to download folder - all is okay. But some torrents can even can be with ? in names, if download with something like qbittorrent - there will be normal filenames.

**Comment by qu1ck** [comment]
On your screenshot there seems to be trouble with all `й` chars. But here is a screenshot with them displaying correctly for me

![image](https://github.com/openscopeproject/TrguiNG/assets/3622532/cd809bdd-6381-4af1-8b6a-9cf7209c6370)

To troubleshoot this I'll need more information:
1. What is your OS, transmission server OS, what are regional settings on both.
2. Do you use webui or the app version of TrguiNG and which version
3. Do you see this issue with all torrents or only this particular one. Try [this](magnet:?xt=urn:btih:a18544fa51e490a2f68281ea9b4351771b0ed5b5&dn=rutor.info_C%D0%B1%D0%BE%D1%80%D0%BD%D0%B8%D0%BA+%D0%BA%D0%BD%D0%B8%D0%B3+-+%C2%AB%D0%9F%D0%BE%D0%BF%D0%B0%D0%B4%D0%B0%D0%BD%D1%86%D1%8B.+%D0%9D%D0%B0%D0%B7%D0%B0%D0%B4+%D0%B2+%D0%A1%D0%A1%D0%A1%D0%A0%C2%BB+%5B1005+%D0%BA%D0%BD%D0%B8%D0%B3%5D+%282010-2023%29+FB2&tr=udp://opentor.net:6969&tr=http://retracker.local/announce) for example.
4. Do you see this issue if you use other GUI or native web ui?
5. Do you see this issue if you **add** the torrent through other GUI or native web ui?

**Comment by AlexK744** [comment]
I have exactly the same problem.
1. Windows 10, regional is russian
2. Both
3. Problem with all torrents contain this symbol
![I](https://github.com/openscopeproject/TrguiNG/assets/150684909/40ee8db6-4985-4755-9006-95a52ff21a73)
![I1](https://github.com/openscopeproject/TrguiNG/assets/150684909/acbbd899-ee3e-440a-b472-4b8033acc778)
5. The native web interface also does not draw the “й” symbol
6. Apparently the problem is not interface dependent.

**Comment by sHAsHiLx** [comment]
> 1. What is your OS, transmission server OS, what are regional settings on both.

My OS Windows 11, server OS Windows Server 2022
Regional settings on my computer

```
PS C:\Users\shashilx> GET-WinSystemLocale

LCID             Name             DisplayName
----             ----             -----------
1049             ru-RU            Русский (Россия)

```
Regional settings on server

`PS C:\Users\shashilx> GET-WinSystemLocale

LCID             Name             DisplayName
----             ----             -----------
1049             ru-RU            Русский (Россия)`


> 
>     2. Do you use webui or the app version of TrguiNG and which version

App
> 
>     3. Do you see this issue with all torrents or only this particular one. Try this for example.
> 
> 
> ```
> magnet:?xt=urn:btih:a18544fa51e490a2f68281ea9b4351771b0ed5b5&dn=rutor.info_C%D0%B1%D0%BE%D1%80%D0%BD%D0%B8%D0%BA+%D0%BA%D0%BD%D0%B8%D0%B3+-+%C2%AB%D0%9F%D0%BE%D0%BF%D0%B0%D0%B4%D0%B0%D0%BD%D1%86%D1%8B.+%D0%9D%D0%B0%D0%B7%D0%B0%D0%B4+%D0%B2+%D0%A1%D0%A1%D0%A1%D0%A0%C2%BB+%5B1005+%D0%BA%D0%BD%D0%B8%D0%B3%5D+%282010-2023%29+FB2&tr=udp://opentor.net:6969&tr=http://retracker.local/announce
> ```

The same problem
![изображение](https://github.com/openscopeproject/TrguiNG/assets/20460472/b00e8065-50cc-4d0d-a92d-0177fd0df718)


> 
>     4. Do you see this issue if you use other GUI or native web ui?
> 

Never before when using Transmission Remote GUI 5.18

>     5. Do you see this issue if you **add** the torrent through other GUI or native web ui?

I'm only adding torrent using app so can't check this.

**Comment by AlexK744** [comment]
![I2](https://github.com/openscopeproject/TrguiNG/assets/150684909/e1aa0bbb-49ed-4f14-90c5-b212a6313880)
Transgui 5.18 also has display problems with "И" and "Й" letters

**Comment by sHAsHiLx** [comment]
![изображение](https://github.com/openscopeproject/TrguiNG/assets/20460472/d8ab9dc9-5ab9-4814-82fd-4a5fa09dac40)
Yes transgui have the same problem with displaying й character.

**Comment by qu1ck** [comment]
Looks like you see this issue even on native web ui and with a torrent added through magnet link. That means it's transmission server issue, not TrguiNG issue.

You should report this on transmission repo https://github.com/transmission/transmission/issues

One thing you could try is set server regional settings to force utf8 for all programs.

![image](https://github.com/openscopeproject/TrguiNG/assets/3622532/253bdae6-2893-4f49-83ce-a86b2c7b1e5a)
![image](https://github.com/openscopeproject/TrguiNG/assets/3622532/cbc1d79b-7061-4ebc-9264-fe00d9142bc8)

**Comment by AlexK744** [comment]
> One thing you could try is set server regional settings to force utf8 for all programs.

Yes, enabling this setting solves the problem
