### ISSUE TITLE
Add torrent controls to right click menu

### ISSUE THREAD

**Issue by PrimozR** [openscopeproject/TrguiNG#118]
Stop/start/pause controls are not only available in the top control bar. Add them to the right click menu - changing the status of the torrent is much quicker this way as there is no need to flail around the monitor with the mouse to reach the control buttons, the right click menu items are much closer. Most clients already do this. Including original Transmission Remote GUI.,

**Comment by qu1ck** [comment]
Pressing F3/F4 is even quicker. But yeah, if move/set labels are duplicated in the menu then start/stop should be too.

**Comment by qu1ck** [comment]
Implemented in [v1.1.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v1.1.0)
