### ISSUE TITLE
Fresh installation of 0.3.0 on macOS doesn't open any GUI

### ISSUE THREAD

**Issue by Qonstrukt** [openscopeproject/TrguiNG#12]
I've downloaded the latest 0.3.0 release, set it's attributes correctly using:
```
xattr -cr /Applications/TrguiNG.app
```
Then started the app, but it doesn't show anything, no windows pop up. The context menus are empty and all actions that are there, like Switch to fullscreen don't do anything.
Then after a minute or so, the app just quits itself.

Console logs: https://gist.github.com/Qonstrukt/6c431ce578cc1e74e92775dca1fd3d16

**Comment by qu1ck** [comment]
Macos issues are the hardest for me to troubleshoot because I don't have a mac. Let me see what I can do.

If any mac dev out there wants to help it would be greatly appreciated.

**Comment by qu1ck** [comment]
Fixed in [v0.4.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v0.4.0).

**Comment by Qonstrukt** [comment]
Thanks, works great now 😄 
Looks and feels very nice for a non-native application I have to say, great job!
