### ISSUE TITLE
Add Torrent Dialog Missing Browse Button

### ISSUE THREAD

**Issue by russellhq** [openscopeproject/TrguiNG#120]
Running latest version of the web interface (v1.0.0) and version 4.0.4 of transmission.

When I click the add torrent file button and select a torrent file, the "Add Torrent" dialog does not show the browse button like you can see in the Wiki. All I get is this:

![image](https://github.com/openscopeproject/TrguiNG/assets/34144023/79fbf4cf-acf3-4c7f-9320-3ff4f2a44270)

**Comment by qu1ck** [comment]
Web interface does not have it because your browser can not access file system of your server and there is no path mapping feature in web interface either.
