### ISSUE TITLE
Prepare for sequential downloading feature in 4.1.x

### ISSUE THREAD

**Issue by Pentaphon** [openscopeproject/TrguiNG#122]
Merged in https://github.com/transmission/transmission/pull/4795

No official GUI yet but is requested at https://github.com/transmission/transmission/issues/6257

**Comment by qu1ck** [comment]
Already supported in current release, check torrent properties dialog.

But I need to hide the checkbox for old transmission versions.

**Comment by qu1ck** [comment]
Looks like transmission has not bumped rpc version yet so I can't commit the fix to hide the checkbox, otherwise it will not appear even if you have current dev build of transmission that supports it. So I'll wait for 4.1 release.

**Comment by qu1ck** [comment]
Note, feature is currently broken in latest dev build https://github.com/transmission/transmission/issues/6365

**Comment by VitanovG** [comment]
Thank you for this feature, I specifically switched to transmission for this feature, but then the original Web GUI has no support for it. Do you know if there is a nightly build, or stable release that currently supports the sequential downloading? I tried transmission 4.0.5 stable and a 4.1.0 nightly, but if I run transmission-remote -si they both give back daemon version: 3.0.0 and rpc version: 16, so the sequential downloading box is disabled in Trguing.

**Comment by qu1ck** [comment]
The nightly should work, make sure you restart your daemon after upgrading.

**Comment by Pentaphon** [comment]
@qu1ck new PR to look at https://github.com/transmission/transmission/pull/7047
