### ISSUE TITLE
Disable tray icon

### ISSUE THREAD

**Issue by fir3-1ce** [openscopeproject/TrguiNG#124]
Is there a way to completely disable the tray icon? I don't need it, and it shows up as 3 dots instead of anything resembling it's native icon. Is it supposed to look like this?

![Screenshot from 2023-12-16 11-01-35](https://github.com/openscopeproject/TrguiNG/assets/113863279/20803999-d2ed-4035-8b9a-47212aac6556)

This is what it looks like on GNOME 42 with Dash to Panel. Other than that, everything else is great. Thanks

**Comment by qu1ck** [comment]
That looks like panel auto hiding icons that are not whitelisted. Try tinkering with panel settings, you probably can set it to show TrguiNG icon. Some panels/desktop environments also let you hide it completely.

It's also possible that icon is buggy if you use flatpak on an old system, unfortunately that area of linux is not well standardized and it's hard to make the icon work universally on all systems. Compiling the app yourself may solve the issue.

There is currently no way to disable the icon completely, it is necessary for window hiding functionality. But a feature can be added to hide the icon as well as disable window hiding.

**Comment by fir3-1ce** [comment]
Appindicator support on Gnome is... wonky, to say the least. I believe the Gnome team officially dropped support for appindicators altogether a while back.

I boot into an Xorg session today, and the icon finally looks the way it should. I don't know what that was about on Wayland, as TrguiNG was the only app with that problem, although I have messed with a lot of configs and themes in the past on this machine

**Comment by qu1ck** [comment]
On wayland I even main window icon does not work sometimes, tauri does not support it properly. Just wayland things ¯\\_(ツ)_/¯

Are you using flatpak build or compiling yourself? If you are compiling then pull the latest, I added the option to hide the tray icon.

**Comment by fir3-1ce** [comment]
I'm using the Flatpak build. I tried to compile it myself last night, but apparently my version of Rust wont let me use let...else statements without upgrading to the nightly build

**Comment by qu1ck** [comment]
Implemented in [v1.1.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v1.1.0)

**Comment by fir3-1ce** [comment]
> Implemented in [v1.1.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v1.1.0)

Now it won't open for me at all in Ubuntu 22.04:

``thread 'main' panicked at /run/build/TrguiNG/cargo/vendor/tauri-runtime-wry-0.14.3/src/lib.rs:2021:55:
called `Result::unwrap()` on an `Err` value: Unknown { .. } - "Unknown error while interacting with the clipboard: Display parsing error"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace``

**Comment by qu1ck** [comment]
What is your desktop environment? You are still using flatpak, right? What is the output if you run with `RUST_BACKTRACE=1` variable?
You can not start v1.1 at all, you didn't get to change settings, is that correct?

**Comment by qu1ck** [comment]
Also if you are using wayland, can you try x11 session?

**Comment by qu1ck** [comment]
Nevermind, I figured out the issue, it is caused by tauri update.

**Comment by qu1ck** [comment]
You can track this issue in #131, in the meantime either roll back to v1.0.0, use x11 or compile yourself as the issue seems limited to flatpak on wayland.
