### ISSUE TITLE
Allow users to reorder torrent properties tabs

### ISSUE THREAD

**Issue by Pentaphon** [openscopeproject/TrguiNG#129]
Can we have the ability to reorder the tabs in the torrent properties section? I'd like to order them the same way as another WebUI to make things more familiar to me. I'd like to make it "General > Peers > Trackers > Pieces > Files" instead. Thanks.

**Comment by qu1ck** [comment]
![image](https://github.com/openscopeproject/TrguiNG/assets/3622532/0a9aa937-13d8-4349-b549-4d7277153039)

**Comment by qu1ck** [comment]
Implemented in [v1.2.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v1.2.0)
