### ISSUE TITLE
Add drag-and-drop support for adding new files

### ISSUE THREAD

**Issue by enchained** [openscopeproject/TrguiNG#13]
Currently there is no way to drag-and-drop a torrent file (at least on v0.3.0 in Windows 11), and you can only add it via Add torrent file button. It would be nice if we could drag the files from browser downloads or a folder to the client window, like with transgui.

**Comment by qu1ck** [comment]
To clarify, I understand people are used to different methods or are using different HID devices that make some actions easier than others. I will still probably add drag-n-drop at some point, just want to make sure you are aware that the straightforward file association and double click in explorer works.

**Comment by enchained** [comment]
> Isn't it easier to just double click the torrent file?

In my case it is already associated with a different local client. I add to my local client more often than to a remote one, since the remote one is mostly for automated/large downloads. I know I can right-click "Open with", but it adds quite a few steps, since there's no "Open with" menu in the Chrome downloads bar, while the files are draggable right from there. 

Also, transgui allows dragging multiple files at once, which can be useful, but will require additional support for the add dialog queue I suppose. As for the add dialog itself, it would be nice if we could switch the server from there too, since when you double-click to open, it may open to a different server tab than you wanted (when you have more than one).

> To clarify, I understand people are used to different methods or are using different HID devices that make some actions easier than others. I will still probably add drag-n-drop at some point, just want to make sure you are aware that the straightforward file association and double click in explorer works.

Thanks, I'll appreciate if that feature will appear at some point.

**Comment by qu1ck** [comment]
Better way to switch tabs when adding torrents is coming but for now you can ctrl-tab or ctrl-shift-tab to switch.

**Comment by qu1ck** [comment]
Fixed in [v0.5.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v0.5.0)
