### ISSUE TITLE
Option to close when minimised

### ISSUE THREAD

**Issue by peskdale** [openscopeproject/TrguiNG#130]
It would be great for the "When minimized" action to have the option to "close" the application to system tray in the same way that the "When closed" action can. i.e. Shut down the web view and reduce resource usage.

![image](https://github.com/openscopeproject/TrguiNG/assets/5855217/9e32bb8f-8a61-418f-af47-a6e807ab0a31)

**Comment by qu1ck** [comment]
That is intentional, minimize is supposed to be fast.

If you don't want to use close button to do "close" action then you can do it from the tray icon menu. On windows also left click on tray icon toggles the window.
