### ISSUE TITLE
Failed to parse torrent

### ISSUE THREAD

**Issue by sHAsHiLx** [openscopeproject/TrguiNG#132]
![изображение](https://github.com/openscopeproject/TrguiNG/assets/20460472/7851d886-6e34-4739-89c7-3c4d2031e315)

Any torrent from this tracker bitru[dot]org - failed to parse torrent. Loading via webui - no any problems torrent just added and started downloading.

**Comment by qu1ck** [comment]
That tracker has technically invalid torrent files because they don't comply with "dictionaries must have keys in sorted order" rule in [BEP3](https://www.bittorrent.org/beps/bep_0003.html#bencoding).

That said, ignoring that rule will not break anything, I will relax this on TrguiNG side.

**Comment by qu1ck** [comment]
Fixed in [v1.2.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v1.2.0)
