### ISSUE TITLE
Feature request: tracker list editing, dedupe when adding trackers to avoid rejection

### ISSUE THREAD

**Issue by Willian-Zhang** [openscopeproject/TrguiNG#134]
expected: adding new trackers
actual: "tracker edit failed" with no detailed reason given

**Comment by qu1ck** [comment]
What is your transmission server version?

**Comment by Willian-Zhang** [comment]
> What is your transmission server version?

4.0.5

**Comment by qu1ck** [comment]
Can you post screenshot of the error?
Also what do you put in trackers list? It's possible the data is malformed and server is rejecting it, not TrguiNG.

**Comment by Willian-Zhang** [comment]
I tried removing empty lines from new added trackers, but same error, an observation is that there are empty lines from an existing torrent (before editing).

**Comment by Willian-Zhang** [comment]
And I just found out cmd+v for pasting on macOS doesn't work in track list editing

**Comment by Willian-Zhang** [comment]
> I tried removing empty lines from new added trackers, but same error, an observation is that there are empty lines from an existing torrent (before editing).

I'm aware of the line saying empty line between tiers. Just not sure if that's causing some parsing problem

**Comment by Willian-Zhang** [comment]
> Also what do you put in trackers list?
a fully qualified tracker, copied from existing one.
e.g.
before edit
```
AAA
BBB

CCC
DDD
```
after
```
AAA
BBB

CCC
DDD
BBB
```

**Comment by qu1ck** [comment]
Transmission does not allow repeating tracker.

**Comment by Willian-Zhang** [comment]
>  It's possible the data is malformed and server is rejecting it, not TrguiNG.

It would not appear on transmission remote.app

**Comment by Willian-Zhang** [comment]
> Transmission does not allow repeating tracker.

Alright! Sorry for my quick judge, must have been the other app had done some dedupeing

**Comment by qu1ck** [comment]
Fixed in [v1.2.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v1.2.0)
