### ISSUE TITLE
What means Ratio and U/D? Is there any difference?

### ISSUE THREAD

**Issue by Dukobpa3** [openscopeproject/TrguiNG#136]
I thought it is same numbers but noticed that some torrents shows different values in this two fields.
(In my case this 4 from list of about couple hundreds)

Can someone explain what the difference?

<img width="596" alt="Screenshot 2024-01-05 at 17 30 27" src="https://github.com/openscopeproject/TrguiNG/assets/1858880/cc5cd482-30e4-4acb-93ef-5d7e9dfa6ee9">

**Comment by qu1ck** [comment]
U/D field is calculated by TrguiNG as a simple fraction of upload/download. 
Ratio field is sent from transmission server, it calculates it differently, see https://github.com/openscopeproject/TrguiNG/discussions/83 and links within.

**Comment by Dukobpa3** [comment]
Here is two cases when ratio shows much more right info than U/D

Something what uploading during downloading
<img width="602" alt="Screenshot 2024-01-05 at 21 50 45" src="https://github.com/openscopeproject/TrguiNG/assets/1858880/05691763-c762-43fc-b6e5-e6d92e7a26ee">

This one shows infinity, like nothing downloaded. But this one was redownloaded from old torrent file to the same folder and file.
This concrete case is the same as server-side ratio because there is not anything uploaded for now. But even I start uploading – there will be infinity.
<img width="558" alt="Screenshot 2024-01-05 at 21 51 37" src="https://github.com/openscopeproject/TrguiNG/assets/1858880/8a73c003-ea49-44ac-809d-fefeea255251">

**Comment by qu1ck** [comment]
Exactly, that's why there are 2 fields.
