### ISSUE TITLE
Condence directory tree if there is no branches

### ISSUE THREAD

**Issue by Dukobpa3** [openscopeproject/TrguiNG#138]
Something like Idea/Rider shows packages and folders

If there is no branchig – couple segments shows in one row

Here `M:\Torrents\` could be one part of tree in one line until I add some another folder beside `Torrents`
<img width="186" alt="Screenshot 2024-01-06 at 17 47 46" src="https://github.com/openscopeproject/TrguiNG/assets/1858880/560a29ce-9814-489a-8031-cb28c33e7653">

**Comment by Dukobpa3** [comment]
Hold my beer
Almost done, will push soon 🥲

**Comment by Dukobpa3** [comment]
pew-pew

<img width="354" alt="Screenshot 2024-01-07 at 02 42 52" src="https://github.com/openscopeproject/TrguiNG/assets/1858880/05cf3694-29cd-44a1-84c8-13eef68bdd6a">

**Comment by Dukobpa3** [comment]
Done but im not sure it became better with this change

<img width="337" alt="Screenshot 2024-01-07 at 04 00 21" src="https://github.com/openscopeproject/TrguiNG/assets/1858880/3e980acd-3f13-4fe1-9c25-c227e04fcc8f">
<img width="333" alt="Screenshot 2024-01-07 at 04 00 38" src="https://github.com/openscopeproject/TrguiNG/assets/1858880/38446367-2e80-4c06-9e01-7e516f2dc6da">
<img width="340" alt="Screenshot 2024-01-07 at 04 00 56" src="https://github.com/openscopeproject/TrguiNG/assets/1858880/34739cc7-17cc-4623-8eaa-bab5f4cda568">
<img width="344" alt="Screenshot 2024-01-07 at 04 01 14" src="https://github.com/openscopeproject/TrguiNG/assets/1858880/52b01916-88bb-4786-92cc-0d66c5143601">

**Comment by qu1ck** [comment]
Implemented in [v1.2.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v1.2.0)
