### ISSUE TITLE
Add Transmission icon as favicon for tab

### ISSUE THREAD

**Issue by Pentaphon** [openscopeproject/TrguiNG#14]
There's no favicon for the tab in the WebUI. Please add it to the tab the WebUI is in, along with perhaps, the transfer speed? It currently only shows the network location of the GUI.

**Comment by qu1ck** [comment]
Great suggestion, will be in next version.

**Comment by qu1ck** [comment]
Implemented in [v0.4.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v0.4.0).
