### ISSUE TITLE
Make bulk tags editing similar to Radarr

### ISSUE THREAD

**Issue by Dukobpa3** [openscopeproject/TrguiNG#142]
In Radarr we can choose multiple movies, then select "edit tags"
And there we can add or remove tags on current movies selection
The main point is – I can add tag to whole selection and not affect other tags on each movie. Or I can remove some tag from each movie and not affect other tags
![Screenshot 2024-01-09 at 16 31 23](https://github.com/openscopeproject/TrguiNG/assets/1858880/d083e884-7301-4874-ab97-3e4d75efa435)
![Screenshot 2024-01-09 at 16 32 12](https://github.com/openscopeproject/TrguiNG/assets/1858880/0f40d7f7-a3f8-46ff-bbc1-3665789674d0)

In TrguiNG in case of bulk editing I will have bunch of movies with same tags after this operation.
<img width="1028" alt="Screenshot 2024-01-09 at 16 37 31" src="https://github.com/openscopeproject/TrguiNG/assets/1858880/60aac35e-7229-48dd-b9fc-6c57a86a51f0">

**Comment by qu1ck** [comment]
Transmission has only one api: set labels on given torrents. It does not have "add" or "remove" labels.
To implement what you ask TrguiNG would need to make 2*n requests of getting current tags, calculating new set of tags and setting tags for each torrent. It opens a whole can of worms for consistency and error handling issues that I don't want to get into.

So unless new transmission apis become available to do that in single request, this is unlikely to be ever implemented. And I don't think transmission wants to go there either, they are even deprecating similar existing apis for trackers (see trackerList replacing previous trackerAdd, trackerRemove).

Don't expect transmission to become a media library, there is software designed for that.
