### ISSUE TITLE
Show overall UL & DL speeds in the status bar

### ISSUE THREAD

**Issue by jpovixwm** [openscopeproject/TrguiNG#143]
At the moment, the download and upload speeds shown in the status bar only show the combined speed of torrents that are visible in the list. I wonder if this is by design, because both Transgui and qBittorrent show the total speed of the entire client, irrespective of which torrents are visible in the table.
I can contribute a fix for this, but the thing that needs to be done depends on whether the current behavior is intended or not.
If it's intentional, then I would add the global speed to the status bar, but if it's a bug I'd just change it to show the global speed.

**Comment by qu1ck** [comment]
Yes, it is intentional. It's more functional too, it provides an easy way to view total stats for a subset of torrents and if you want full total just click "All torrents" filter.
Separate number will be only more confusing.

If you want you can add an interface setting (can be build into the section menu like the compact directories setting in filters section menu) that will toggle "always show full totals".

**Comment by Dukobpa3** [comment]
I like it implemented as now.
Just choose all torrents to see whole speed.

I'm using this feature a lot while seeding to private trackers.

**Comment by jpovixwm** [comment]
Thanks for the feedback. I can see how the current implementation can be useful too. I thought about something simple, such as this: 
![image](https://github.com/openscopeproject/TrguiNG/assets/53523617/609c182b-31b8-4845-ba18-d04fdc8c8963)
The globe icon is supposed to convey that the displayed rate is global. There's one drawback to this approach, though - the bandwidth limits are shown twice if you enable both status bar items.

> If you want you can add an interface setting [...] that will toggle "always show full totals".

This idea is not bad either, but if it was worded this way, then the user could reasonably expect the "Total" status (which shows the total size in bytes of visible torrents) to also start displaying the global size of all torrents. And then there's no way to see both global and visible-only totals simultaneously😕

Perhaps the "Total" item could be renamed to "Shown" or "Visible" and changed to behave similar to "Selected"?
![image](https://github.com/openscopeproject/TrguiNG/assets/53523617/303739cf-d2ce-4038-8cce-95a0dc387b9e)
In this case, the "show global totals" toggle could only apply to the UL/DL speeds.

**Comment by Dukobpa3** [comment]
There just can be 2 additional marks – "Download speed global/upload speed global"
And use it not as toggle between global/selection but as on your first screen, if selected all 4
<img width="713" alt="Screenshot 2024-01-14 at 12 53 33" src="https://github.com/openscopeproject/TrguiNG/assets/1858880/f9f6d0e4-4bb6-42b3-8974-930d94d9e6f9">

**Comment by qu1ck** [comment]
Not a fan of adding more items in the status bar or making total show more. There is barely enough space to show current info as is on smaller laptop screens.

> then the user could reasonably expect the "Total" status (which shows the total size in bytes of visible torrents) to also start displaying the global size of all torrents

Text can be changed to "Shown" or "Filtered" when always show full totals is disabled.

> And then there's no way to see both global and visible-only totals simultaneously😕

I can't think of a not contrived situation when you would want this.

**Comment by jpovixwm** [comment]
Yeah, that's what I had in mind too. I just don't like displaying the bandwidth limit twice, and can't think of an elegant solution around that without resorting to some hack such as only showing the bandwidth limit on the first "speed" status bar item or something.

Currently I've made it like this:
![trguing_CtyZNa9wG7](https://github.com/openscopeproject/TrguiNG/assets/53523617/c4c9c174-d69d-40c2-8ade-ebec99999154)
And to me it seems like a good middle ground overall.

**Comment by qu1ck** [comment]
Looks good to me
