### ISSUE TITLE
Tracker URL mass update

### ISSUE THREAD

**Issue by Algwyn** [openscopeproject/TrguiNG#144]
From time to time it is necessary to perform a mass update of tracker URLs.
Editing of tracker list is only enabled when a single torrent is selected (macOS version).
It would be great if this could be enable when multiple torrents are selected.

When selected torrents have different tracker lists, a default behavior should be set, such as: 
* warning that current tracker lists will be overwritten
* tracker list defaulted to the list of the first torrent selected

**Comment by qu1ck** [comment]
That's exactly how it works now in v1.1 (sans the warning), get the latest version.

**Comment by Algwyn** [comment]
I'm using v.1.1.0, macOS build x86 and trackers menu option is disabled when multiple torrents are selected.

Version: v1.1.0
Frontend: WebKit 605.1.15 (WebKit 605.1.15) on Mac OS 10.15.7
Build date: 27/12/2023, 07:09:27

**Comment by qu1ck** [comment]
Then you must have older transmission server pre v4. Old API makes it hard to bulk update multiple torrent trackers so it is disabled for old servers.

**Comment by Algwyn** [comment]
Transmission server is transmission-daemon-4.0.5, recentrly upgraded from v3.
Is there some set-up to change on the server to enable bulk update ?

**Comment by qu1ck** [comment]
No, just restart TrguiNG once after you updated the server. Check in the statusbar, it shows current version of the server.

**Comment by Algwyn** [comment]
Oups ... restarting the server fixed the issue. Should have checked that first .
Many thanks for your help. Works perfectly!
