### ISSUE TITLE
"Done" column not updating during download

### ISSUE THREAD

**Issue by Algwyn** [openscopeproject/TrguiNG#148]
I've noticed that the "Done" column status is not updating while the torrent is downloading:

<img width="244" alt="image" src="https://github.com/openscopeproject/TrguiNG/assets/5394928/176914c1-e165-4871-9e5d-5805c1523cf1">

The downloading of these two torrents was a bit slow, so the lack of update after 20 minutes of downloading was quite noticeable.
In the "Details" window pane, the "Downloaded" progress bar in the "General" tab, and the "Pieces" tab are not updating either.

Server: 
> transmission-daemon 4.0.5 (a6fe2a64aa)

Client:
> Version v1.1.0
> Frontend WebKit 605.1.15 (WebKit 605.1.15) on Mac OS 10.15.7
> Build date 27/12/2023, 07:09:27
>

**Comment by Algwyn** [comment]
Probably server issue.

**Comment by qu1ck** [comment]
Yes, if other numbers are updating and "Done" isn't it's likely because your server is getting bad data. Check hashfails stat in details.
