### ISSUE TITLE
UI inconsistency: Alternative bandwidth icon location

### ISSUE THREAD

**Issue by Algwyn** [openscopeproject/TrguiNG#152]
I believe that there is a minor UI inconsistency in the location of the alternative bandwidth icon.
It is located in the left side of the icon bar, together with icons which are related to torrent-level actions.

Toggling the Alternative bandwidth is a server-level setting.  It would be more consistent to locate this icon between the layout icon and the server settings icon, in the right side of the icon bar.

**Comment by qu1ck** [comment]
That's one way to look at it but I prefer it in the left group because it's relatively frequently used. 
Buttons on the right are supposed to be set once and forget.
