### ISSUE TITLE
Don't remember checkbox "Delete torrent data" when removing torrents

### ISSUE THREAD

**Issue by veyley** [openscopeproject/TrguiNG#155]
The "Delete torrent data" should be reset every time you remove a torrent. Currently it remembers the setting which can accidentally prompt you to delete torrent data on completed torrent entries.

**Comment by qu1ck** [comment]
I like current behavior and tried to reduce risk of accidental deletions by changing the text of the red confirm button from "Remove" to "Delete" but probably an option to always reset the flag is still a good idea.

**Comment by qu1ck** [comment]
Implemented in [v1.2.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v1.2.0)
