### ISSUE TITLE
Path Mapping Configure

### ISSUE THREAD

**Issue by JustAndreww** [openscopeproject/TrguiNG#157]
Hello!

I have installed transmission on NAS and trying to map folders on NAS <--> network drives on Windows PC.

On NAS I have folder `/volume4/Video `where I want to download videos using installed transmission client.
On Windows I mount this folder into Network driver with letter `V:\`. 

So I'm adding following line in mapping settings:
`"/volume4/Video=V:/"`

But after adding torrent from Windows PC and specifying `V:\` as download path I got "Error: Download directory path is no absolute".

So what I did wrong? Or that's not how it suppose to work?

Thanks!

**Comment by Cris--** [comment]
I'm in same boat. Same config like above but didn't work if i try to open a complete file from GUI.

`/volume1/transmission=Z:/`
Syno NAS download folder = Windows network drive (same place like NAS download folder)

Also why at hell a slash / and not a backslash \ for the windows path?

**Comment by qu1ck** [comment]
Windows understands both `/` and `\`. But you need consistent trailing slash, either on both parts of path mapping or neither like this: `/volume1/transmission=Z:`

**Comment by Cris--** [comment]
Ok, thanks for the info. Yes, z:/ works in Explorer   -- rofl, 30 years IT and always something new!

But i get still an Error opening path. Doesn't matter what i try. File is 100%x complete and a text file (or other files). Nothing special. All network related actions are working normal (smb, network drive, no firewall or  anything else).

/volume1/transmission=Z:
/volume1/transmission=Z:/

**Comment by qu1ck** [comment]
Give me an example of a full file path that exists on your nas and what it looks like on your windows mount.
