### ISSUE TITLE
Issue with "Open Folder" functionality while downloading file (Windows)

### ISSUE THREAD

**Issue by JustAndreww** [openscopeproject/TrguiNG#159]
If you will try to use Open Folder button on file that is currently being downloaded it would fail to do so and instead will try to open file.

![image](https://github.com/openscopeproject/TrguiNG/assets/4374611/d9af766b-8559-4a1e-933f-cd7ae7ecdefa)
Note that you need to download a single file (for example ZIP) and when you do the Open Folder the file download should be in progress.

OS: Windows 10 (22H2, 19045.2604)
GPU: RXT 3060
WebView2 runtime ver: 121.0.2277.98
TrguiNG ver: [v1.1.0](https://github.com/openscopeproject/TrguiNG/tree/v1.1.0)

**Comment by qu1ck** [comment]
Fixed in [v1.2.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v1.2.0)
