### ISSUE TITLE
Can't hide the info pane at the bottom of the window

### ISSUE THREAD

**Issue by mshapcotte** [openscopeproject/TrguiNG#16]
Can't hide the info pane at the bottom of the window (Windows version 0.4.0)

**Comment by qu1ck** [comment]
Yes, you can't remove it but you can make it pretty small. That's intentional.

Is there a reason why you want to hide it?

**Comment by mshapcotte** [comment]
I often have little use for that pane, and prefer as little visual clutter (and more room for torrent list) as possible. A minor quibble though. TrguiNG is pretty amazing and no doubt all the long time 'transgui' users will flock to it. (Your post [there](https://github.com/transmission-remote-gui/transgui/discussions/1420#discussioncomment-6199686) is how I found this project!)

**Comment by mshapcotte** [comment]
Lovely -- 'just cloned and compiled "v0.4.0-5-g3144a30-dirty," took it for a spin on Windows, and both the GUI and keyboard shortcut toggles for both the filters and details panes work as one would expect. Thanks! ('Dunno if it's cool to close the issue myself, but I consider it closed!)

**Comment by qu1ck** [comment]
I close issues when the changes make it to the release because not everyone compiles the code themselves. You can close it since you like to live on the edge :)
