### ISSUE TITLE
Non-Latin characters in torrent name are rendered incorrectly

### ISSUE THREAD

**Issue by StentMan** [openscopeproject/TrguiNG#163]
I tried using a different, like Ariel Unicode MS which is very complete, but that didn't help at all, it still renders pretty much the same. A restart didn't help as well.
![image](https://github.com/openscopeproject/TrguiNG/assets/6360751/e14a6f27-8548-4915-9bba-b872eb78f531)

Also, I can't use the _Open Folder_ feature when that happens.

Anything I can do to fix this?

**Comment by qu1ck** [comment]
Check transmission's own web ui, does it show correctly there? If not, it's a server issue. I've seen this with Cyrillic too. Usually updating the server to later version helps.

**Comment by qu1ck** [comment]
Also on windows try forcing utf8
https://github.com/openscopeproject/TrguiNG/issues/114#issuecomment-1808656282

**Comment by StentMan** [comment]
I've been using Transmission Daemon with Transmission Remote GUI without any issue that the thought never crossed my mind. You were correct on both accounts:
1. In the web UI it looked exactly like in TrguiNG.
2. Updating to the latest version (4.0.4 -> 4.0.5 in my case) did the trick.

Thank you!
