### ISSUE TITLE
Is it possible to remove entries from the history list of recent locations?

### ISSUE THREAD

**Issue by StentMan** [openscopeproject/TrguiNG#165]
I'm asking about the list that pops-up when you click on the icon that looks like a clock in the add torrent screen or the Move... (F6) options when right-clicking a torrent.

If not, please consider this as a feature request.

**Edit:** Should've added I'm using version 1.1.0 on Windows 10.

**Comment by qu1ck** [comment]
There is no way to do it from the app yet.

You can edit the config file manually in the meantime, it's in `%APPDATA%\trguing.json`

**Comment by StentMan** [comment]
Thank you.
btw, why not place it in a folder of its own, something like %APPDATA%\TrguiNG\trguing.json?

**Comment by qu1ck** [comment]
Mainly because it's not necessary, that is the only file the app needs to store. If there ever is a need to store more I'll migrate it to a subdirectory.
