### ISSUE TITLE
Feature Request: Ability to rename folder dir before adding a torrent to download list

### ISSUE THREAD

**Issue by JustAndreww** [openscopeproject/TrguiNG#166]
Not really important but quite nice feature imo:
![image](https://github.com/openscopeproject/TrguiNG/assets/4374611/a7b22aa6-e8ef-43d3-b72e-52551561be04)

**Comment by qu1ck** [comment]
See https://github.com/openscopeproject/TrguiNG/issues/88#issuecomment-1769318492
