### ISSUE TITLE
Up speed / Down speed fields not displaying data in version 1.2.0

### ISSUE THREAD

**Issue by numericOverflow** [openscopeproject/TrguiNG#171]
Speed fields not displaying, but progress bar looks OK.  Backend Transmission server (v2.94) is running on Ubuntu.

Note the comparison screenshot to Transmission Remote GUI app to show it's not a server backend problem.  Screenshots were captured about 1 minute apart so data should have been in RPC.

TrguiNG was just installed fresh (no previous versions) from [this](https://github.com/openscopeproject/TrguiNG/releases/download/v1.2.0/TrguiNG_1.2.0_x64_en-US.msi) MSI file.

![2024-02-27_114945](https://github.com/openscopeproject/TrguiNG/assets/3429424/5846d9d1-ccf6-4967-a632-ec130f437199)

**Comment by qu1ck** [comment]
Transmission Remote GUI does averaging across period of time so what it shows is not necessarily what the server reports. It will keep showing speeds for a while after actual speeds are 0, TrguiNG will not.

**Comment by numericOverflow** [comment]
@qu1ck - I understand what your saying, but in the example above I'm actively downloading so there should be a speed to display in the download field.  I wouldn't expect that it's a left-over average rate discrepancy as you suggest.  So far I have not seen *any* speeds in the summary table despite there being activity as the files go from 0% --> 100% complete.

Notice in this additional screenshot, the detail section at bottom shows a speed value, but it's just not displayed in the summary table.  I did some trimming of the screenshot but only to protect the names of the innocent and compact for clarity sake, not to fudge any numbers.

It also looks like the GUI title bar isn't updating with the current active transfer rates either (shows 0B/s Down & 0B/s Up) despite real up/down activity happening on server.

![2024-02-27_114945a](https://github.com/openscopeproject/TrguiNG/assets/3429424/00700ae2-c742-4206-8869-ce360da57bf0)

**Comment by qu1ck** [comment]
Well, that is strange, I can't reproduce it and I tested it on 2.94 server too.

Can you open devtools (F12) network tab, check the api request and response? There may be lots of activity there, make sure to find a request/response pair where multiple torrents are requested. Do fields `rateDownload/rateUpload` have positive numbers there?

![image](https://github.com/openscopeproject/TrguiNG/assets/3622532/aa1e685c-2761-4261-a362-e3fad18ca924)

**Comment by numericOverflow** [comment]
Here you go:

I redacted valid integer values with "XXXXXXXXXX"

```
"queuePosition": XXXXXXXXXX,
"rateDownload": 1024000,  
"rateUpload": 0,
"recheckProgress": 0,
"secondsDownloading": XXXXXXXXXX,
"secondsSeeding": 0,
"seedIdleLimit": XXXXXXXXXX,
"seedIdleMode": 0,
"seedRatioLimit": XXXXXXXXXX,
"seedRatioMode": 0,
"sizeWhenDone": XXXXXXXXXX,
"startDate": XXXXXXXXXX,
"status": 4,
"torrentFile": "/var/lib/transmission-daemon/.config/transmission-daemon/torrents/ThisActiveTorrent.torrent",
"totalSize": XXXXXXXXXX,
"trackerStats": [REDACTED]
```

**Comment by qu1ck** [comment]
And this is from a response with multiple torrents, not single one? Because TrguiNG makes separate requests to show data in the torrent table and in torrent details, the latter being single torrent request with all fields, former is multi torrent request with only fields necessary to show the table.

If so then I have no idea what's going on because "rateDownload": 1024000 should show as "1000 KB/s"

**Comment by qu1ck** [comment]
All I can suggest in this case is to update to newer server version, 2.94 is like 10 years old. Maybe you are running into an old bug.

**Comment by numericOverflow** [comment]
Yeah, I probably should update....  Closing ticket as it's not an issue for TrguiNG to solve.

**Comment by numericOverflow** [comment]
BTW - I finally updated to Transmission v4 and your GUI displays rates flawlessly.  I guess the ancient v2.94 was the source of my troubles.
