### ISSUE TITLE
Icon OCD - Directory + icon cut off Safari 17.3.1

### ISSUE THREAD

**Issue by bbsixzz** [openscopeproject/TrguiNG#172]
Thank you for this amazing webui, absolutely gorgeous.

![Screenshot 2024-02-28 at 21 17 53](https://github.com/openscopeproject/TrguiNG/assets/47334163/b46a9edf-df69-4a9c-a2bf-f8d37e0653cd)

**Comment by qu1ck** [comment]
For what it's worth, this happens sometimes on windows too
![image](https://github.com/openscopeproject/TrguiNG/assets/3622532/21f977b3-880e-472d-ae8e-5587defab021)

**Comment by qu1ck** [comment]
Fixed in [v1.3.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v1.3.0)
