### ISSUE TITLE
Flatpak crash on wayland with some desktops

### ISSUE THREAD

**Issue by inboxman** [openscopeproject/TrguiNG#173]
Reports this error:

thread 'main' panicked at /run/build/TrguiNG/cargo/vendor/tauri-runtime-wry-0.14.4/src/lib.rs:2022:55:
called `Result::unwrap()` on an `Err` value: Unknown { .. } - "Unknown error while interacting with the clipboard: $DISPLAY variable not set and no value was provided explicitly"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Installed from flathub on Endeavour OS.

**Comment by qu1ck** [comment]
This is a an issue with some wayland desktop environments and flatpak/tauri combination. See workarounds in https://github.com/openscopeproject/TrguiNG/issues/131#issuecomment-1961805590

**Comment by inboxman** [comment]
> This is a an issue with some wayland desktop environments and flatpak/tauri combination. See workarounds in [#131 (comment)](https://github.com/openscopeproject/TrguiNG/issues/131#issuecomment-1961805590)

Thanks for the quick response.

**Comment by qu1ck** [comment]
Since Endeavour OS is based on Arch maybe you can also try the arch AUR package? https://aur.archlinux.org/packages/trgui-ng

**Comment by qu1ck** [comment]
Should be fixed in [v1.3.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v1.3.0) (flatpak version will be out soon)
