### ISSUE TITLE
Feature request: saved directory history

### ISSUE THREAD

**Issue by Algwyn** [openscopeproject/TrguiNG#174]
It would be nice to be able to delete saved directories from history, and to record in history directories used with the "Move" button

Typical use case: typing mistake results in wrong directory in history. After using "Move" to correct the issue, the incorrect directory remains in the history, and the correct directory specified with "Move" is not recorded in history. 

Recording directories used with "Move" should be easiest to implement and would help avoiding future mistakes (both correct and incorrect directories would appear in history)

The ability to delete directories from the history could be implemented by adding a "delete" mark at the right of each line in the history dropdown (similar to the feature enabling to delete a URL from chrome autocomplete)

**Comment by Algwyn** [comment]
Many thanks for the fix! that was quick!

**Comment by Algwyn** [comment]
Very minor cosmetic detail: the width of the path history dropdown jumps when the mouse goes over long paths, as the delete icon is added to the line. The issue appears only when there are long paths in the history which results in the length of the path + width of icon to be longer than the width of the dropdown.

Could be fixed by having the delete icon float over the path name, like the "Edit" icon in the Torrent name column.

**Comment by Algwyn** [comment]
Some may find that this feature is dangerous and may result in path deletion by mistake.

I see two options to avoid mistakes:
- add a confirmation dialog
- turn the path line in red when the mouse is over the delete icon to give a visual clue that clicking the mouse will delete the path

**Comment by qu1ck** [comment]
There is nothing dangerous about this feature, it does not delete any files, only removes a path from history.

The jumping width can not be avoided unless the space for the icon is reserved all the time which I think is worse. Unlike the torrent name column which is fixed width and longer text is just cut off, the path can not be cut off because you would not be able to distinguish long paths that only differ in the last portion.

**Comment by qu1ck** [comment]
Implemented in [v1.3.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v1.3.0)
