### ISSUE TITLE
Add torrent by magnet link does not reset the previous link

### ISSUE THREAD

**Issue by enchained** [openscopeproject/TrguiNG#18]
My first thought was that it was an auto-paste from the clipboard, but looks like it was the link I entered before that.

I think it would be also nice to have an auto-paste in that dialog, with an indication that the link was pasted from the clipboard, but only if it's an opt-in setting and not the default behavior, since not everyone likes that.

**Comment by qu1ck** [comment]
Fixed the stale link in the dialog.

The clipboard thing I consider to be a massive security hole, no app should monitor clipboard, especially an app that is supposed to be talking to outside servers. Browsers prohibit it, so it's impossible in web version. It is technically possible (although not trivial) in app version but I am not going to implement it mostly for security reasons.

**Comment by melyux** [comment]
psst this issue can be closed @qu1ck @enchained

**Comment by qu1ck** [comment]
Fixed in [v0.5.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v0.5.0)
