### ISSUE TITLE
desktop file

### ISSUE THREAD

**Issue by username227** [openscopeproject/TrguiNG#184]
On the latest commit, the desktop file used in the arch pkgbuild, which is taken from the flathub repo, needs to be updataed. The desktop file includes the environment variable that had been necessary to allow the program to render using webkit2gtk on nvidia cards due to the rust quirk.

Now that the issue has been resolved, using that environment variable actually gives a white screen, while deleting the environment variable renders normally. Therefore, we should update the desktop file to remove the environment variable. I would do this myself and propose the commit but it's not in this repo and I dont know the current status of the flatpak build.

If the flatpak desktop file can't be updated yet, then maybe we should bring the desktop file into repo here.

**Comment by username227** [comment]
Update: apparently this was true as of two or three commits ago. At least, that was my experience yesterday or the day before. When I just tried it again today, it worked fine on both. So perhaps it's not as critical as I thought it was. But the env variable is no longer necessary in any case and can be removed. If the white screen pops up again i'll update here again.

**Comment by qu1ck** [comment]
I have encountered white screen with non-nvidia graphics too so having it seems to be more widely compatible. I'm inclined to keep it, at least for now.
