### ISSUE TITLE
Errored torrents should show "error" status instead of "seeding" status?

### ISSUE THREAD

**Issue by Pentaphon** [openscopeproject/TrguiNG#187]
Just noticed that you gave "error" torrents a red progressbar, which is great and thanks for that. 

However, they are still showing as "seeding" instead of being classified as "error" status. 

![error](https://github.com/openscopeproject/TrguiNG/assets/49374058/3c5e9ec3-18a0-4233-86ef-d27b5c30da6e)

Not sure if you want to change this but I thought I'd mention it for the sake of keeping things consistent since an errored torrent is no longer technically able to seed. Not sure if the Transmission spec allows for this?

**Comment by qu1ck** [comment]
It's because TrguiNG considers torrents with errors on main tracker to be errored. Transmission can still seed them through DHT/peer exchange and does not consider them to be in error state. This is intentional.

**Comment by Pentaphon** [comment]
>It's because TrguiNG considers torrents with errors on main tracker to be errored. Transmission can still seed them through DHT/peer exchange and does not consider them to be in error state. This is intentional.

Gotcha. Just wanted to run it by you since I just noticed it. I will close this.
