### ISSUE TITLE
feature request: add `Seeding` filter

### ISSUE THREAD

**Issue by trim21** [openscopeproject/TrguiNG#189]
hope we could have a new filter with `filter: (t) => t.status === Status.seeding`

**Comment by qu1ck** [comment]
You can already do that, it is equivalent to selecting "Completed" + "Running" at the same time (use ctrl-click)

![image](https://github.com/openscopeproject/TrguiNG/assets/3622532/477f8c7b-5b20-463e-a4ca-b0d6cb186506)

**Comment by trim21** [comment]
where is running... I'm using 1.3.0 from latest release
![image](https://github.com/openscopeproject/TrguiNG/assets/13553903/4937288e-6555-403a-a24e-bb5053210f28)

**Comment by qu1ck** [comment]
Enable it through right click menu.

**Comment by trim21** [comment]
OK， thanks
