### ISSUE TITLE
how to reset browser to default state?

### ISSUE THREAD

**Issue by trim21** [openscopeproject/TrguiNG#190]
I run in to a weird bug. I'm using browser with TrguiNG.
I tried this repo and switch to a translated fork (https://github.com/jayzcoder/TrguiNG), then I try to swich back to this repo.

Then I encounter a error like this:

![image](https://github.com/openscopeproject/TrguiNG/assets/13553903/827a45e5-7788-4907-bb60-9e485f2a4044)

I tried with clear cookies and localSession or disable all extension, even reset data for domain, non of them works. is there any other place I need to reset?

**Comment by trim21** [comment]
fixed by restart whole browser...

**Comment by qu1ck** [comment]
For the record only thing TrguiNG web saves is config in localstorage. Delete "trguing-config" entry from dev tools application tab and you should be able to restart cleanly.
Resetting data for domain should work too.

**Comment by trim21** [comment]
Thanks, I think i encounter a bug of browser itself.
