### ISSUE TITLE
"Error: incomplete torrents directory path is not absolute" thrown when "Use separate directory for incomplete files" is unticked and "Path for incomplete files" is empty

### ISSUE THREAD

**Issue by n3mur1t0r** [openscopeproject/TrguiNG#192]
Whenever I click save on Server settings, it keeps throwing this error even though I don't want to use a separate directory for incomplete torrents.

![image](https://github.com/openscopeproject/TrguiNG/assets/5160880/30c38e06-e35c-446e-9cbd-966646653914)

**Comment by qu1ck** [comment]
It has to be a valid path anyway, just copy the download path. The error is coming from the server btw, not TrguiNG.

**Comment by n3mur1t0r** [comment]
It doesn’t appear to come from the server, since I changed some settings in the web UI and saved, and no error was thrown.

**Comment by n3mur1t0r** [comment]
Thank you for your time, I did that and it works fine.
