### ISSUE TITLE
can not copy error message...

### ISSUE THREAD

**Issue by trim21** [openscopeproject/TrguiNG#195]
I have a usecase to copy file path in error message, but I can only copy magnet of this torrent...

![image](https://github.com/openscopeproject/TrguiNG/assets/13553903/49073f7f-5699-497e-800b-4541f09bb558)

**Comment by qu1ck** [comment]
Right-click -> Copy

![image](https://github.com/openscopeproject/TrguiNG/assets/3622532/f912e2f3-d7af-4883-8343-06b46303cbce)

The ctrl-c bind is intentionally global and your use case is rare so I don't think this needs to be changed.
Fields that are more often expected to be copied are made into text fields where ctrl-c still works (for example path or hash).

**Comment by trim21** [comment]
thanks
