### ISSUE TITLE
Can information about the width, display, and order of header fields be saved locally?

### ISSUE THREAD

**Issue by kidzgy** [openscopeproject/TrguiNG#197]
Can information about the width, display, and order of header fields be saved locally?

Currently, the configuration information such as the width and order of the header for "Name" and "Speed" is saved in the browser cache, so if you change the browser, you have to reset the configuration information, which is very troublesome, and it is not interoperable with the exe program.

Is it possible to add an option to save these table header configuration information locally instead of the browser cache, in this case, no matter how to change the browser to clear the cache or even use the exe, this information can be saved without having to reconfigure.

Thanks!

**Comment by qu1ck** [comment]
Yes, settings export/import can be added. Though I should be careful on how config versioning would work. Until now I only cared about newer version extending old config, with export/import I need to consider how older version will overwrite/merge with newer one as well.

**Comment by kidzgy** [comment]
I think we can discard the idea that the new version is compatible with the old version, which is still saved in the browser cache, while the new version can only support configuration import and export and the ability to check whether to save locally or not.

With a major version update like this, reconfiguration is necessary. Thankfully, the first reconfiguration doesn't take much time, but the convenience of using the exe as well as the web in subsequent versions is greatly enhanced.

**Comment by qu1ck** [comment]
It's not relevant now but when the new version will become old version then it will be.

**Comment by qu1ck** [comment]
Added in [v1.4.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v1.4.0)
