### ISSUE TITLE
[MacOS] add mime type associations

### ISSUE THREAD

**Issue by qu1ck** [openscopeproject/TrguiNG#2]
Custom plists are not currently supported in Tauri but when they are:

https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundledocumenttypes
https://github.com/transmission/transmission/blob/main/macosx/Info.plist

**Comment by qu1ck** [comment]
I found a way to customize the plist file but it's not enough. Apple being apple has completely custom way to handle opening files and urls, you have to process special events kind of like this (example is for 'GURL' or get url event)

https://github.com/FabianLars/tauri-plugin-deep-link/blob/main/src/macos.rs

I have yet to find an example of processing 'odoc' event.

**Comment by melyux** [comment]
This is working great now with both .torrent files and magnet links, awesome

**Comment by qu1ck** [comment]
Fixed in [v0.5.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v0.5.0)
