### ISSUE TITLE
Reassign double-click function for web-ui users

### ISSUE THREAD

**Issue by Steve-Brule** [openscopeproject/TrguiNG#20]
When double-clicking a torrent in the web-ui an error pops up, saying "Error opening path". Doubtful that'd be possible to do from a browser, so instead it'd be nice to implement another function for double-click (or at least remove the current function to prevent confusion).

Some ideas for other double-click functions would be start/stop the torrent or open the properties window for the torrent.

**Comment by qu1ck** [comment]
Good suggestion, implemented.

I was planning to also support a sort of "open" action by opening a tab to a preconfigured url with torrent/file path substituted in query or path variable. Idea is to combine it with some sort of web file manager/viewer. That will be an option later.

**Comment by qu1ck** [comment]
Fixed in [v0.5.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v0.5.0)
