### ISSUE TITLE
Please give us an option to list saved download directories in alphabetical order

### ISSUE THREAD

**Issue by CitizenJohnJohn** [openscopeproject/TrguiNG#200]
The dropdown for saved download directories is currently in time order, with most recent at the top. I'd find this more intuitive if it could be sorted by alpha order.

Thanks!

**Comment by azlux** [comment]
No agree, you more likely need your last directory than a old one.
I've hundred of folders, this list is already not really useful in my case, so last entries are better (or having sorted as an option ?)

The best option should be to have the "Download Directory" pre-filled with the folder we select on the left "Directory" menu.

**Comment by azlux** [comment]
Hoo, I didn't saw the commit with the sort as option. Sorry for my answer

**Comment by qu1ck** [comment]
Added in [v1.4.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v1.4.0)
