### ISSUE TITLE
Feature request: Add support for clicking on magnet: links for the Web Interface

### ISSUE THREAD

**Issue by normanr** [openscopeproject/TrguiNG#203]
Similar to https://github.com/transmission/transmission/issues/346. The PR (https://github.com/transmission/transmission/pull/2874) could be used as a basis for adding the feature.

**Comment by qu1ck** [comment]
Seems useful but because the handler registration api requires secure context this limits the feature to transmission running on localhost or behind a reverse proxy with ssl termination. This leaves out users running transmission on a separate device in local network.

**Comment by normanr** [comment]
> Seems useful but because the handler registration api requires secure context this limits the feature to transmission running on localhost or behind a reverse proxy with ssl termination. This leaves out users running transmission on a separate device in local network.

Agreed. I have my transmission behind a reverse proxy secured with a Let's Encrypt certificate, which wasn't too hard to set up, but it does require additional configuration.

**Comment by qu1ck** [comment]
Added in [v1.4.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v1.4.0)
