### ISSUE TITLE
Feature request: ability to set "upload-slots-per-torrent" parameter

### ISSUE THREAD

**Issue by iridial** [openscopeproject/TrguiNG#204]
Hello, I was wondering if it'd be possible to be able to edit the parameter `upload-slots-per-torrent` found in the settings.json file, via this web interface, and make it effective without having to restart transmission.

https://github.com/transmission/transmission/blob/main/docs/Editing-Configuration-Files.md#bandwidth

Thanks!

**Comment by qu1ck** [comment]
It's not in the API so, unfortunately no. https://github.com/transmission/transmission/blob/main/docs/rpc-spec.md

You should open an issue on transmission repo to have this added to the api and once it's there feel free to reopen this.
