### ISSUE TITLE
Feature Request: Add the ability to change the torrent name and directory name like qbittorrent.

### ISSUE THREAD

**Issue by gnailam** [openscopeproject/TrguiNG#205]
![屏幕截图 2024-05-21 023231](https://github.com/openscopeproject/TrguiNG/assets/132273883/fcf746b5-a56a-4080-8a7c-f71f01031da1)
![屏幕截图 2024-05-21 023313](https://github.com/openscopeproject/TrguiNG/assets/132273883/fb28814c-fcd0-4fb0-993e-b702debdb88b)

**Comment by qu1ck** [comment]
Hover over the name and press the button (or F2 after selecting the row)
![image](https://github.com/openscopeproject/TrguiNG/assets/3622532/8278c0ff-2166-4c5f-a617-865743c5e3e4)
