### ISSUE TITLE
Apple Silicon build is broken

### ISSUE THREAD

**Issue by maur1th** [openscopeproject/TrguiNG#206]
Hi!

In https://github.com/openscopeproject/TrguiNG/releases/tag/v1.3.0, opening `TrguiNG_aarch64.app.tar.gz` results in:

<img width="372" alt="Screenshot 2024-05-24 at 07 44 12" src="https://github.com/openscopeproject/TrguiNG/assets/5855076/82fa0e51-3494-48aa-993c-01ecd0d8d681">

However, the x64 build does work.

I'm available to help if you don't have an Apple Silicon Mac around.

**Comment by qu1ck** [comment]
Did you reset the attributes with `xattr` as instructed on the download page?

Can you try if 1.2 or any previous aarch64 build works?
