### ISSUE TITLE
Feat: Prepare to enable download first and last piece first + sequential mode in 1 toggle. 

### ISSUE THREAD

**Issue by Pentaphon** [openscopeproject/TrguiNG#207]
Transmission 4.1.x will have "Download first and last pieces first" functionality combined with "sequential download mode" according to https://github.com/transmission/transmission/pull/6893 and since the contributor combined both functions, I have opened an issue to create 1 GUI toggle to enable both functions at the same time in https://github.com/transmission/transmission/issues/6257 which I hope to see in TrguiNG as well. 

Not yet merged but highly requested feature and goes beyond qBittorrent by having both functions become enabled in 1 GUI toggle instead of 2 toggles. Just opening this issue to keep track.

**Comment by qu1ck** [comment]
Sequential download is already supported in TrguiNG. The  MR you linked does not affect the api and does not require any changes on TrguiNG side.

**Comment by Pentaphon** [comment]
> The MR you linked does not affect the api and does not require any changes on TrguiNG side.

Might want to mention in the UI that "download first and last pieces first" is now also included in the toggle?

**Comment by qu1ck** [comment]
That is a server side implementation detail that 99% of users will not care about.
