### ISSUE TITLE
Option to hide the tab strip

### ISSUE THREAD

**Issue by Cris--** [openscopeproject/TrguiNG#208]
Hi,

add a tab-less mode please. I use only one server so the space is wasted here for me.
The config buttons  needs a replace then i think.

Re-ordering the columns via drag n drop would be also great.

Anyway great and modern fork, thx!

**Comment by qu1ck** [comment]
You can reorder columns with drag and drop in the context menu of the header.
I'll rename the issue to be only about hiding the tab strip.

**Comment by Cris--** [comment]
> You can reorder columns with drag and drop in the context menu of the header. I'll rename the issue to be only about hiding the tab strip.

Dough, now i see  ^^

**Comment by qu1ck** [comment]
Added in [v1.4.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v1.4.0)
