### ISSUE TITLE
Add full-size home screen icon for Firefox/Chrome users?

### ISSUE THREAD

**Issue by Pentaphon** [openscopeproject/TrguiNG#21]
Since this is a WebUI rather than a simple webpage, I think it needs a full-size new tab page icon along with the favicon for the tab. 

Can we get a full-size icon for the new tab page like the one Trakt has in the below screenshot? Here's how it currently looks on Firefox.

![ff](https://github.com/openscopeproject/TrguiNG/assets/49374058/75c748c5-1ac6-4d2d-8807-12b17ed1021c)

**Comment by qu1ck** [comment]
Where is that screenshot from? Recently visited sites in empty tab?

I'm not sure how firefox determines what to show there, I can try adding multiple favicons with different sizes and hope that firefox will choose to display a bigger one. This area is not well standardized.

**Comment by Pentaphon** [comment]
> Recently visited sites in empty tab?

Yep!

**Comment by Pentaphon** [comment]
> Where is that screenshot from? Recently visited sites in empty tab?

Yep

> I'm not sure how firefox determines what to show there, I can try adding multiple favicons with different sizes and hope that firefox will choose to display a bigger one. This area is not well standardized.

https://stackoverflow.com/questions/48231953/how-firefox-creates-the-website-tiles-in-new-tab

**Comment by qu1ck** [comment]
Fixed in [v0.5.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v0.5.0)
