### ISSUE TITLE
Add torrent or magnet popup's tab order

### ISSUE THREAD

**Issue by bluenlive** [openscopeproject/TrguiNG#212]
Hello.
Thank you for the good program.

When the "Add Torrent" popup appears, the tab is not positioned on the "Add" button.
So, if you select a torrent with the keyboard, you have to move it to the "Add" button. (Shift-Tab twice, maybe)

It looks like a fix to move the initial position of the tab to "Add" is needed.

**Comment by qu1ck** [comment]
Which version are you using? I think it's fixed in the latest version, at least it works for me.

**Comment by qu1ck** [comment]
I found that in my previous fix I missed the add magnet dialog so it did not get correct focus. But your description is confusing and you are mentioning torrents instead of magnets multiple times so I'm not 100% sure this fixes it for you.

**Comment by bluenlive** [comment]
That's right.
I mistakenly thought the two dialogs were the same.
Only the tab order of the Magnet dialog needs to be modified.
Thank you.

**Comment by qu1ck** [comment]
Fixed in [v1.4.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v1.4.0)
