### ISSUE TITLE
Feature Request: More comprehensive "copy' function similar to qBittorrent

### ISSUE THREAD

**Issue by Pentaphon** [openscopeproject/TrguiNG#214]
Instead of just copying the magnet link, I'd like to see a copy function that copies different things according to your use case like qBittorrent does to also get the name or plain info hash. You might also add more keyboard shortcuts for this. 

![image](https://github.com/user-attachments/assets/2fc43c36-eff0-452b-8d7c-9ace13033e19)

**Comment by qu1ck** [comment]
I don't think this provides better UI than just copying from text fields in details panel.
![image](https://github.com/user-attachments/assets/a381d81a-77bd-4275-b9c6-2fa2092fd105)

**Comment by Pentaphon** [comment]
> I don't think this provides better UI than just copying from text fields in details panel.

You're probably right. I just thought it would be nice to have the copy functions all in one place with the mouse. I'll close.
