### ISSUE TITLE
Short(er) Tracker display in torrent list

### ISSUE THREAD

**Issue by starmoonxp** [openscopeproject/TrguiNG#221]
Could you consider to trancat the tracker displayed in the torrent list to save column space and easy to read.

1. remove protocol string ("http://" or "https://")
2. remove domain prefix "tracker."
3. (optional) remove suffix top domain. (.com .org or so)

**Comment by qu1ck** [comment]
1. Where do you see that? I don't see it anywhere, only on very old transmission servers, in which case update your server.
2. It is useful sometimes so it will be configurable which prefixes you want to hide. See #213
3. Nah, doesn't save any space and it's important part of domain.

**Comment by starmoonxp** [comment]
![image](https://github.com/user-attachments/assets/420b1594-4407-4992-99be-8fba524fd804)
I mean the tracker displayed here. anywhere else will still display the full URI of tracker.

**Comment by qu1ck** [comment]
And what is your transmission server version?

**Comment by starmoonxp** [comment]
> And what is your transmission server version?

I'm now using Transmission 3.0. But it dosen't seem matter with the daemon version. (I think.) An old transmission-remote-dotnet did this and I think it maybe useful.  Many PT users will care about the which site(tracker) a torrent is downloading from.

**Comment by qu1ck** [comment]
Update to 4.0 and you will not see https prefix.

**Comment by starmoonxp** [comment]
> Update to 4.0 and you will not see https prefix.

I will do but many devices with build in transmission are not easy to upgrade by enduser. 

I've attaced what tracker was displayed by trasmisson-remote-dotnet as a reference. I'm loving transmission-remote-dotnet but it's being 10 years since last updated and it's java based and very slow.

**Comment by starmoonxp** [comment]
> 1. Where do you see that? I don't see it anywhere, only on very old transmission servers, in which case update your server.
> 2. It is useful sometimes so it will be configurable which prefixes you want to hide. See [Add the ability for users to add their own subdomains to tracker exclusion list #213](https://github.com/openscopeproject/TrguiNG/issues/213)
> 3. Nah, doesn't save any space and it's important part of domain.

I followed the link here and saw many want this simular feature.  I wish you can make it happen in either way.

**Comment by qu1ck** [comment]
Fixed in [v1.4.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v1.4.0)
