### ISSUE TITLE
Allow to Store conf in Remote(Server Side)

### ISSUE THREAD

**Issue by once375ml** [openscopeproject/TrguiNG#222]
Please allow to store configuration, like columns, widths, options... in server side. As when I access webui from Lan, QuickConnect and DDNS from different locations, I have to configure 3 times for each machine. And I have 3 synology NAS.

Usually, who using webui, has the write pemission of transmission daemon for remote configuration store.

**Comment by qu1ck** [comment]
Transmission api does not support this.

However I already added feature to export/import the settings so you will be able to configure your client once, export that config and then quickly import it on other clients or instances. See #197, this will be in next release.
