### ISSUE TITLE
Seeds/Peers column sorting

### ISSUE THREAD

**Issue by mahkitah** [openscopeproject/TrguiNG#23]
Thanks for adding the totals to the Seeds and Peers columns.
But the sorting behaviour of these columns isn't optimal yet. As far as I can see the totals aren't used for sorting.

IMO sorting a la qbittorrent is best: connected first, total second:
1 / 12
1 / 10
0 / 35
0 / 24
etc.

Some clients sort by totals alone which is still better than by connected alone.

**Comment by qu1ck** [comment]
Fixed in [v0.5.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v0.5.0)
