### ISSUE TITLE
feature request: Delete the torrent if the same torrent exists on other trackers.

### ISSUE THREAD

**Issue by ButterflyMurders** [openscopeproject/TrguiNG#240]
For all torrents of a specific tracker: delete the torrent if the same torrent exists on other trackers (without deleting local data); keep the torrent if it does not exist on other trackers.

**Comment by qu1ck** [comment]
I don't understand what you are asking. Transmission deduplicates torrents, same torrent can not exist in multiple instances for different trackers.
