### ISSUE TITLE
Port test functionality is confusing

### ISSUE THREAD

**Issue by Steve-Brule** [openscopeproject/TrguiNG#25]
When using the test port function to check if the listening port is forwarded correctly, it will always check the old port, no matter what is in the listening port input field.

To clarify:
I switched VPN providers, and thus my listening port had to change, too. I went to change the listening port in trguing's settings, but when I typed in my new port, the check failed. Turns out, I firstly needed to click "save", and only then would the test be performed on the new port. It took me a few minutes to figure out and it is not very intuitive.

**Comment by qu1ck** [comment]
Technically it's checking the port that is saved in transmission, I'm limited by the way API is designed. I should add a hint to save the settings if currently shown port is different from daemon settings port.

**Comment by Steve-Brule** [comment]
Either a hint or an automatic save on test button click before the port test is performed, if the port field was modified.

**Comment by qu1ck** [comment]
It's not a good UI to do a save action in a button that doesn't suggest any save action. And handling rollback if user presses cancel after testing changed port is much more effort than this issue warrants, a text hint will do.

**Comment by qu1ck** [comment]
Implemented in [v0.6.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v0.6.0).
