### ISSUE TITLE
An expanded flags column for Peers

### ISSUE THREAD

**Issue by melyux** [openscopeproject/TrguiNG#26]
Something I really wanted in other clients is for them to decipher the Peers tab's flags column for me. Really bad at memorizing them. Could have a separate column for it. Plenty of width real estate in that tab since there isn't a lot of other information, so it could be comma separated string for each flag. [Flag meanings](https://forum.transmissionbt.com/viewtopic.php?t=10894)

Like this for "K?I":

"Unchoked by peer but not interested, unchoked peer but not interested, incoming"

**Comment by qu1ck** [comment]
More up to date list here https://github.com/transmission/transmission/blob/main/docs/Peer-Status-Text.md

Sometimes I wish BT protocol used language that is a bit less BDSM lol. Choking, leeching, "if they would let us". Need to read actual BEPs to understand what they actually mean sometimes.

**Comment by melyux** [comment]
Looking at the chart, I think it's better to display them with columns based on mutual exclusivity/grouping:

Encrypted: (Yes/No)
From: (Tracker/DHT/PEX)
Connection: (Incoming/uTP)
Operation: (Downloading/Uploading/Download if they let us/Upload if they let us/We're not interested/They're not interested/Optimistic)

From my rough understanding of the relationships between the flags, I mean

**Comment by qu1ck** [comment]
![image](https://github.com/openscopeproject/TrguiNG/assets/3622532/ac321cab-5771-4db3-94f0-436af38a1eae)

**Comment by melyux** [comment]
Very nice. This is officially better than the native client itself

**Comment by melyux** [comment]
@qu1ck Could we make the peer "Have" column a progress bar like the torrent "Done" column?

**Comment by qu1ck** [comment]
I don't think it makes sense here since their % is out of our control and sometimes is not even supposed to reach 100% if they don't want all files.

**Comment by melyux** [comment]
Eh the native client uses progress bars for peers' percentages and it's mostly for adding some quick visual hints more than anything, I think it would be good
