### ISSUE TITLE
Windows and Linux remote path mapping conflict

### ISSUE THREAD

**Issue by enchained** [openscopeproject/TrguiNG#27]
I use TrguiNG client on Windows 11, and Transmission server on Docker (Linux). My downloads folder path inside the Docker container is `/downloads`, and on Windows it is mounted under `\\DISKSTATION\homes\enchained\downloads`. I mapped them together in the TrguiNG settings.

When I try to open a remote folder on Windows, TrguiNG gives me this error:
```
Error opening path
\\DISKSTATION\homes\enchained\downloads/sonarr/my-downloaded-folder
```

This folder can be manually located at this path in the Windows Explorer:
```
\\DISKSTATION\homes\enchained\downloads\sonarr\my-downloaded-folder
```

Looks like the subfolder paths given by the Transmission server should be converted to the ones compatible with the host system of the TrguiNG client.

**Comment by qu1ck** [comment]
They are compatible, that's not the issue.
I have a very similar setup to yours and it works fine for me (windows 10).

Do your network shares have auth enabled? Try mounting them in windows as a network drive, that alone may help. If it doesn't then try using that mounted drive path instead of `\\host\share` syntax.

**Comment by enchained** [comment]
My network share has auth, and looks like I can't map it to a network drive until I'll set up SSL on my home NAS (Synology).

Anyway, right now I can't reproduce the error with exact same path I tried before (I moved the download later, but recreating it does not reproduce either). I tried with a few other downloads and it works correctly. Currently I can see that error only when trying to open downloads which files were removed, but that's expected. I will close the issue for now.

**Comment by qu1ck** [comment]
Not sure what ssl has to do with mounting a smb network share, windows 10 has this feature right in explorer when you open "My Computer"

![image](https://github.com/openscopeproject/TrguiNG/assets/3622532/c641a83c-c7e4-4f26-b6e8-ebe37d591915)

**Comment by enchained** [comment]
I am aware of the feature, but mapping network drives via this dialog does not recognize Synology SMB shares when the server does not have SSL set up. It does not work with server name or IP, despite them opening fine in explorer. From what I gathered, it is a knows Synology-specific issue.
