### ISSUE TITLE
Allow searching files in torrent's files tab?

### ISSUE THREAD

**Issue by Pentaphon** [openscopeproject/TrguiNG#28]
It would be nice to be able to search for a specific file within a torrent's files tab. Not sure if that can be done but thought I'd ask.

**Comment by qu1ck** [comment]
It's possible but needs a good UI. Where to put the search field, should it always be visible, if not how to invoke it, how should the tree be represented flattened or not, etc. I'll think about it.

**Comment by Pentaphon** [comment]
Perhaps the existing torrent search field at the top of the UI can become the file search field when a file in the torrents tab is selected? Then you won't have to add another search field to the UI.

**Comment by qu1ck** [comment]
No, they should be independent, there are situation where you want to use both search fields. Usually torrent first, files second.
Also it would not be clear that you even can use top field for files table search because they are far apart.

**Comment by Pentaphon** [comment]
> No, they should be independent, there are situation where you want to use both search fields. Usually torrent first, files second.
> Also it would not be clear that you even can use top field for files table search because they are far apart.

Fair enough. Just thought it might reduce clutter.

**Comment by qu1ck** [comment]
Implemented as a optional search box on top of the table that you can enable through context menu.

**Comment by qu1ck** [comment]
Implemented in [v0.8.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v0.8.0).
