### ISSUE TITLE
GeoIP lookup info

### ISSUE THREAD

**Issue by qu1ck** [openscopeproject/TrguiNG#3]
Just some relevant links in case if I ever want to implement ip to country lookup that original TransGUI has

https://www.miyuru.lk/geoiplegacy
https://db-ip.com/db/download/ip-to-country-lite

Missing piece is a decent country flags package.

**Comment by qu1ck** [comment]
There is a MIT licensed decent flagpack here https://flagpack.xyz/docs/development/react/

**Comment by qu1ck** [comment]
![image](https://github.com/openscopeproject/TrguiNG/assets/3622532/caeadda7-324f-4caf-93e6-fa2a0492d841)

**Comment by melyux** [comment]
Would emojis not work?

**Comment by qu1ck** [comment]
I wish they did but Microsoft's idea of a flag emoji is a 2 letter iso code in a square.

**Comment by melyux** [comment]
Wow just found out about that whole thing. 🏴‍☠️

**Comment by melyux** [comment]
Works great

**Comment by qu1ck** [comment]
Implemented in [v0.6.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v0.6.0).
