### ISSUE TITLE
Using different icons for "not started" and "fully downloaded" when stopped

### ISSUE THREAD

**Issue by enchained** [openscopeproject/TrguiNG#30]
Currently, whether I add the download without starting it, or the download completes itself and stops, they both have the same yellow icon, and cross-checking the progress bar is needed to see if it's actually done. 

I'm used to a different (green checkmark) icon for completed+stopped downloads in transgui, and I'm wondering whether it would be possible to add here?

**Comment by melyux** [comment]
Would also be good to have a separate icon for magnetized transfers (no metadata) to tell them apart from normally Downloading transfers. If possible

**Comment by qu1ck** [comment]
I added separate icon for completed but stopped torrents but there will not be "finished" status as it discourages seeding. No torrent is ever finished, thou shall seed until the end of the internet or heat death of the universe, whichever comes later. :)

**Comment by melyux** [comment]
Does the Magnetized one really need a separate Metadata percentage column? Could reuse the Done bar to take up less space

**Comment by qu1ck** [comment]
Overloading semantics is bad too, "Done" progress jumping up and then resetting can be confusing. I will disable rarely useful columns soon in default config so metadata column will not waste space unless you want it.

**Comment by melyux** [comment]
It's not that it's not hidden by default, but it's a column that's only useful for a tiny percentage of the time and only relevant to magnetized transfers. With all the data being in a single row, it doesn't really justify the real estate it takes up imo

**Comment by qu1ck** [comment]
There are like 4 native apps that vary significantly in what they do, but that's not the point.

TrguiNG is smart in fetching only fields it needs to display from transmission. It's better to "waste" space with optional column that you can enable in that 1% of situations when you need it than to waste network bandwidth permanently because you have to request the mostly useless column to display combined bar.

**Comment by melyux** [comment]
Wouldn't the proposed combined bar be done on the client side? Just displaying the magnetization progress in a different spot and not displaying the (always 0%) download progress. Why would it take extra requests?

**Comment by qu1ck** [comment]
Most columns in the main torrents table map 1:1 to a field in transmission rpc API. When you disable a column client does not request corresponding data from server. That means disabling "Metadata" column will save bandwidth. But if you have a combined bar that renders based on multiple fields then you can't not request the data and will always have to fetch the extra field from API whether it's useful to you or not.

> Unless you mean the magnetization progress is only grabbed when the column is enabled. Not possible to only grab it for magnetized transfers?

Yep, list of fields you grab is not conditional.

**Comment by Pentaphon** [comment]
> Magnetizing transfers could have their status read "Magnetizing" instead of Downloading to make it clear what the progress bar is indicating

I like this as well. The Transmission project behaves similar to this and they might do some other UI changes to more clearly show this happening as well.

**Comment by qu1ck** [comment]
Implemented in [v0.6.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v0.6.0).

**Comment by enchained** [comment]
> Implemented in [v0.6.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v0.6.0).

In cases when download was added (without starting) via a magnet link, the green icon is displayed, probably because "0 B out of 0 B were downloaded". Is it possible to have the yellow stopped icon for those specific cases?

**Comment by qu1ck** [comment]
Fixed, will be in next version.

**Comment by enchained** [comment]
Another thing I noticed: if I select only some of the files to download, after finishing it has the yellow icon despite it being 100% done (of selected). Is this the intended behavior?

**Comment by qu1ck** [comment]
Not intended, fixed. Thanks for catching.
