### ISSUE TITLE
Add ability to resize / auto-size columns

### ISSUE THREAD

**Issue by wikiped** [openscopeproject/TrguiNG#31]
Currently (v0.5.0-dirty) all columns have the same width and there are no column separators to drag / resize columns.

But otherwise good alternative gui.
Thank you.

**Comment by qu1ck** [comment]
Does the resizer not appear when you hover over the column header?

![image](https://github.com/openscopeproject/TrguiNG/assets/3622532/e0dce2cc-c5db-4188-8322-f20ed2ad48d8)

Post your frontend info, it can be found in application info below the version.

**Comment by melyux** [comment]
Resizing works for me, but auto-resizing when double clicking the resizer would be a good addition

**Comment by qu1ck** [comment]
I looked into auto sizing, it's not easy to implement and given that table contents updates all the time it would be of limited use. Maybe I'll add it at some point but don't expect it soon.

**Comment by Pentaphon** [comment]
I don't really think auto-sizing is very useful here. The existing column sizing is already powerful enough. I prefer tweaking the column sizes myself because auto-sizing usually leads to results that don't suit me.

**Comment by wikiped** [comment]
> Does the resizer not appear when you hover over the column header?

For some reason resizer does not appear. So I thought it was not "supposed" to be there for now, hence the issue.

This is what it looks like for me:

Dark skin:

![image](https://github.com/openscopeproject/TrguiNG/assets/5990528/8c726639-1f71-45a9-8b3d-ec14d526efaf)

White skin:

![image](https://github.com/openscopeproject/TrguiNG/assets/5990528/43724926-83e3-45bf-88d9-47ab54694ca5)

And nothing changes when I hover over the header.

Perhaps a "front-end" issue? This what is shown in "Version Info" window:
`Edge 114.0.1823.67 (Blink 114.0.0.0) on Windows 10`

**Comment by qu1ck** [comment]
Strange, I have exact same edge version on win 10 and I don't have this issue.

Is there anything unusual about your setup, like non standard mouse or maybe you are using remote desktop software?

**Comment by wikiped** [comment]
I can't say there is something unusual - no other program has shown similar symptoms...

I stumbled upon `Inspect` menu which helped to get to html/css properties of header:

![image](https://github.com/openscopeproject/TrguiNG/assets/5990528/a6ae5e00-f5b6-47f4-8bb7-2bf95d32a3a6)

So technically resizer is there, but it's width is `0`, therefore I can't see/drag it.

Are there any "global css properties" that are read from outside of the app or that might have had effected on this property?

**Comment by wikiped** [comment]
I can see that css properties have been read:

![image](https://github.com/openscopeproject/TrguiNG/assets/5990528/2a84ead4-3761-451d-b74d-7ad29651c7fe)

But I also noticed two error messages in the log:

```
DevTools failed to load source map: Could not load content for https://tauri.localhost/main.bundle.css.map: Connection error: net::ERR_CONNECTION_REFUSED
DevTools failed to load source map: Could not load content for https://tauri.localhost/737.bundle.css.map: Connection error: net::ERR_CONNECTION_REFUSED
```

Perhaps the latter is only relevant for DeTools?

I checked my firewall settings for `msedgewebview2.exe` and `trguing.exe` and I don't see any reason why the connection would be refused.

**Comment by qu1ck** [comment]
These rules are supposed to apply and make it narrow and mostly invisible normally but thicker and more visible when hovered over header

https://github.com/openscopeproject/TrguiNG/blob/master/src/css/torrenttable.css#L93-L103

Looks like some styles load but the `@media(hover)` don't, interesting.

**Comment by qu1ck** [comment]
Are you on a laptop with a touchscreen perhaps? That's the only reason I can think of that those wouldn't work. I can rewrite the rules without `@media` query and see if it helps.

**Comment by qu1ck** [comment]
Here, try this build.
[TrguiNG_0.6.0_x64-setup.exe.zip](https://github.com/openscopeproject/TrguiNG/files/11966948/TrguiNG_0.6.0_x64-setup.exe.zip)

**Comment by wikiped** [comment]
> Are you on a laptop with a touchscreen perhaps?

Yes, the laptop is with the touchscreen, but it is not "in use" - the actual display is HDMI connected (perhaps this is unusual...)

Tried new build - and yes, the resizer is now visible and usable. Thank you.
