### ISSUE TITLE
Can't compile latest version

### ISSUE THREAD

**Issue by username227** [openscopeproject/TrguiNG#32]
Interestingly, I cannot compile the latest version, even though I'm not doing anything different. I get the following error message:

  Compiling zbus v3.14.1
error: failed to run custom build command for `trguing v0.6.0 (/home/jerry/TrguiNG/src-tauri)`

Caused by:
  process didn't exit successfully: `/home/jerry/TrguiNG/src-tauri/target/release/build/trguing-f63017be5a7c8708/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=TAURI_CONFIG
  cargo:rerun-if-changed=tauri.conf.json
  cargo:rustc-cfg=desktop
  path matching dbip.mmdb not found.
warning: build failed, waiting for other jobs to finish...
       Error failed to build app: failed to build app

Any idea if anything changed that might cause this?

**Comment by qu1ck** [comment]
There is a new requirement, compilation instructions were updated, check the readme.

**Comment by username227** [comment]
> There is a new requirement, compilation instructions were updated, check the readme.

Got it now. Sorry, my bad. Loving this program, BTW. It has real potential. Thanks for your great work on this.

**Comment by qu1ck** [comment]
No worries, glad you like it.
