### ISSUE TITLE
Display verification progress percentage

### ISSUE THREAD

**Issue by enchained** [openscopeproject/TrguiNG#33]
When I add a large (100GB+) download and force the file verification on it, it can take a while. Currently only the icon and status indicate the verification, but Done % always stays at 100%. 

Most clients that I've used display the progress of verification in the Done column. It it possible to add here?

**Comment by melyux** [comment]
For me, the Done % does show the verification status already.

**Comment by qu1ck** [comment]
It is possible but would be wasteful, same reasoning as here: https://github.com/openscopeproject/TrguiNG/issues/30#issuecomment-1620864004

Verification progress is shown in details panel progress bar, since only one torrent is verified at a time it is enough.

**Comment by melyux** [comment]
It actually does show the Verification progress in the Done bar for me. It may be limited to only when the torrent otherwise has had no progress on it.

**Comment by qu1ck** [comment]
Verification in Done bar shows only when you first add the torrent and data already exists. In that case transmission reports same stats in verification and done percentage, TrguiNG shows what the api returns.
