### ISSUE TITLE
Removing some clutter

### ISSUE THREAD

**Issue by melyux** [openscopeproject/TrguiNG#34]
There are some mostly implicit/useless values that will help remove clutter (as by example from the older Transmission Remote GUI project):

- Show blank instead of "Unknown" for ETA
- Show blank instead of "never" for last active
- Show blank instead of -1 for ratio of magnetized torrents

**Comment by qu1ck** [comment]
Disagree on the first, having no eta is different from unknown eta and should be reflected.

Others are fixed.

**Comment by melyux** [comment]
Some of my seeding transfers have a blank ETA while others have "Unknown", and inactive downloads have blank too. It's all over the place. What does Unknown indicate?

**Comment by qu1ck** [comment]
"Unknown" means ETA field is applicable, but can not be calculated. For example if you have a seeding limit but upload speed is 0 or downloading and download speed is 0. Empty means ETA is not applicable, i.e. torrent will be in current state indefinitely. Transmission api returns distinct values for these.

**Comment by melyux** [comment]
Makes sense for the most part. Maybe instead of "Unknown" it could be a "-" to be less distracting?

**Comment by qu1ck** [comment]
And then I will get questions about what "-" means. Use sorting and filters to present the data as you want it.

**Comment by Pentaphon** [comment]
> * Show blank instead of "Unknown" for ETA

How about the infinity symbol? qBittorrent and uTorrent already do that.

**Comment by qu1ck** [comment]
I like that, actually use it in few other places already.

**Comment by qu1ck** [comment]
Implemented in [v0.7.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v0.7.0)
