### ISSUE TITLE
Wishlist: Trackers Injection from static trackers list

### ISSUE THREAD

**Issue by wikiped** [openscopeproject/TrguiNG#36]
There is an up-to-date [trackers list](https://github.com/ngosang/trackerslist).

The proposal / idea is to add something like `Inject trackers` menu item to context menu of `Trackers` Tab. The list could be chosen / set in settings or as a sub-menu to the above context menu item.

As far as I am aware no other app offers similar functionality so this could a unique feature.

**Comment by Pentaphon** [comment]
This was a new feature in Transmission 4.0.0

>Users can now set "default" trackers that can be used to announce all public torrents.

https://github.com/transmission/transmission/releases/tag/4.0.0

Not sure if this needs to be added upstream first to make it happen via WebUI.

**Comment by qu1ck** [comment]
I like the idea and it will be implemented soon. Default tracker list will be configurable but it will not update automatically, there is no reliable source for such list and there is no universal way to rank trackers on latency or other metrics.

**Comment by Pentaphon** [comment]
> I like the idea and it will be implemented soon. Default tracker list will be configurable but it will not update automatically, there is no reliable source for such list and there is no universal way to rank trackers on latency or other metrics.

Most people just use the trackers_best list from https://github.com/ngosang/trackerslist

**Comment by qu1ck** [comment]
Yes, that was liked above. It's neither reliable nor universal.

**Comment by qu1ck** [comment]
Implemented in [v0.7.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v0.7.0)
