### ISSUE TITLE
Not able to run on macOS Apple Silicon version

### ISSUE THREAD

**Issue by UniverseXXX** [openscopeproject/TrguiNG#4]
Getting - _“TrguiNG” is damaged and can’t be opened. You should move it to the Trash._
Checked settings - security and app not appearing there as it normally would in similar cases.

**Comment by qu1ck** [comment]
This is known issue with unsigned apps. Run this in terminal

`xattr -cr /Applications/TrguiNG.app`

**Comment by qu1ck** [comment]
You mean crashes? Is there an error message? Maybe something in Console reports? https://support.apple.com/guide/console/reports-cnsl664be99a/mac

To avoid reentering connection information you can configure server and exit without opening it. App saves config when the window is closed so if you do it once the server should be there next time you open it.

**Comment by qu1ck** [comment]
I believe this is fixed in [v0.4.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v0.4.0). Let me know if there are still issues.
