### ISSUE TITLE
Transfers/Files/Peers that aren't completely finished round up to 100%

### ISSUE THREAD

**Issue by melyux** [openscopeproject/TrguiNG#40]
When any percentage shown isn't quite 100%, it should stay at 99.9% to indicate that it's not quite done yet.

And hear me out here... what if 100% progress bars turn green?

**Comment by qu1ck** [comment]
Rounding fixed. More color: I heard you... answer is still no :D The status icon changes color and it is visually noticeable if you look for it while being subtle enough.

**Comment by melyux** [comment]
Fair enough, it will live in my private patches ;)

<img width="339" alt="image" src="https://github.com/openscopeproject/TrguiNG/assets/10296053/6bc368d8-c828-468a-a8bd-7298b3424847">

**Comment by qu1ck** [comment]
Whatever percentage transmission reports I round down. If it reports 100% then it will be 100.
Also it's possible you saw a missing piece in details panel but the table was more up to date. They are not always fully in sync because they work based on independent queries of transmission api.

**Comment by qu1ck** [comment]
Found one more place where rounding should be down, that probably fixes what you ran into.

**Comment by Pentaphon** [comment]
> More color: I heard you... answer is still no :D The status icon changes color and it is visually noticeable if you look for it while being subtle enough.

Actually, there is discussion in the Tranmission issues page that is leaning towards my suggestion of having all the Transmission clients follow the Mac client in using the following color scheme for the progress bar and progress has already been made on the Web UI and GTK client https://github.com/transmission/transmission/issues/5648 so if you ever wanted to do what @melyux suggests, this might be a good reason to try some color changes.

**Comment by qu1ck** [comment]
Official transmission clients are very minimalistic and don't have any color. It works for that design.
TrguiNG has a lot more color and already uses color for status, along with icons. I don't plan on changing progress bar colors but would welcome a PR if someone implements it as opt-in config option.

**Comment by melyux** [comment]
I'll submit my patch as a PR, just gotta figure out the setting thing

**Comment by Pentaphon** [comment]
> Official transmission clients are very minimalistic and don't have any color. It works for that design.

Looks like its going to change for 4.1.0 or later because the Mac progress bar colors are going into the Qt, GTK and Web client which a lot of people seem to like, I think it works on the official clients because the progressbar is so big on Transmission compared to other clients so it acts as a very big visual indicator. I do see how it wouldn't work as well on TrguiNG because the UI and progressbar are more of a traditional uTorrent-like design. 

>I don't plan on changing progress bar colors but would welcome a PR if someone implements it as opt-in config option.

This is a welcome choice! Thanks!

>I'll submit my patch as a PR, just gotta figure out the setting thing

Thanks! I was about to suggest that. I'm sure @qu1ck can help you figure that out.

**Comment by qu1ck** [comment]
> I'll submit my patch as a PR, just gotta figure out the setting thing

All you have to do is modify config.ts in 2 places (interface, default setting) and interfacepanel.tsx to modify the value. Make sure the fields in config and in form have same name and it should just work.

**Comment by melyux** [comment]
I have the first draft finished and operational. Testing it on my own for as many combinations as possible before opening PR
