### ISSUE TITLE
Allow adding .torrent file to fortify existing transfer

### ISSUE THREAD

**Issue by melyux** [openscopeproject/TrguiNG#43]
A nice feature from Transmission (and Transmission Remote GUI) is the ability to add .torrent files to existing transfers. If it's an existing magnet transfer, this adds the metadata and trackers. If it's an existing normal transfer, it adds any trackers from the .torrent file that aren't already on the transfer.

Currently in TrguiNG, this doesn't work and instead shows this:
<img width="187" alt="image" src="https://github.com/openscopeproject/TrguiNG/assets/10296053/8e19590a-d7c5-430d-9218-5ce7765f71ff">

**Comment by qu1ck** [comment]
It is a feature that sounds good to have but I never found it useful in practice. In many years of me using transgui I was only reminded of this feature when I accidentally clicked on the same torrent or magnet link twice. How often do you actually run into torrents with matching hashes from different sources?
Can you describe a real scenario when this would be useful?

**Comment by melyux** [comment]
This is one of the most used features for me. Often I'll add magnetized transfers, only to have them sit without metadata for a while. Later during my surfing I'll find a .torrent file and add it later onto the transfer to bootstrap it with the metadata without having the remove the existing transfer (and any metadata I may have changed on it, like seed limit).

As for torrents with matching hashes from different sources, that happens quite often too. Often in the middle of a frenzied search for some long-lost file

**Comment by qu1ck** [comment]
I just checked transgui, it does not do what you say it does with the magnets that can't get metadata. If you give it a torrent with matching hash it will happily add trackers but will not bootstrap metadata from that torrent.

Also looking at code, it uses a deprecated method to add trackers.

**Comment by melyux** [comment]
That's embarrassing. It's been a placebo this whole time? At least the native Transmission app on Mac seems to do it properly.

**Comment by qu1ck** [comment]
The adding trackers part isn't placebo, deprecated method still works, just will be removed at some point.

I can do the trackers part (with correct method) but the metadata part I don't now how it's implemented in the mac app, there is no api for this, it must be done via a delete + re-add in the app itself.

**Comment by Pentaphon** [comment]
> How often do you actually run into torrents with matching hashes from different sources?

I'd say its somewhat common on public trackers because a lot of sites just take the torrent from another site and don't bother changing the torrent but just add different announce URLs to the magnet

**Comment by qu1ck** [comment]
Implemented in [v0.7.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v0.7.0)
