### ISSUE TITLE
Allow uploading multiple torrent files like the official WebUI can?

### ISSUE THREAD

**Issue by Pentaphon** [openscopeproject/TrguiNG#44]
The official Transmission WebUI allows you to upload multiple torrent files at the same time and has a UI that says how many torrents are being uploaded. Can we have the same functionality?

**Comment by qu1ck** [comment]
What UI? File chooser showing how many files were selected?
Because I don't see any UI showing progress of files being uploaded, I'm on 4.0.4.

TrguiNG allows you to upload multiple files too, just drag and drop a bunch. You have to click "Add" for each one but you only have to setup download directory and other stuff once.

**Comment by Pentaphon** [comment]
> What UI? File chooser showing how many files were selected?

The official 4.0.3 WebUI shows this when you select 2 torrents. 

![web](https://github.com/openscopeproject/TrguiNG/assets/49374058/8b359020-f8f6-437d-9bae-d04abe833e5a)

> You have to click "Add" for each one but you only have to setup download directory and other stuff once.

That's what I'd like changed. It seems a bit cumbersome to only be able to add one torrent at a time. It would be nice to be able to select more than one torrent after pressing the add button, the same way the official WebUI does. That kind of feature parity is important when dealing with lots of torrents.

**Comment by qu1ck** [comment]
I added multi file selection and multi upload when you click add button. Drag and drop still works the old way.

**Comment by qu1ck** [comment]
Fixed in [v0.7.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v0.7.0)
