### ISSUE TITLE
Tracker status showing "working" for certain tracker errors

### ISSUE THREAD

**Issue by Steve-Brule** [openscopeproject/TrguiNG#45]
It appears as though the tracker status column interprets "working" a bit too literally.

In one particular example, I have a few torrents that are no longer registered with their respective trackers. By definition, the tracker is working in those torrents, but clearly not in a way that's desirable (simply returning a message about the torrent being unregistered).

Here's an example:
![image](https://github.com/openscopeproject/TrguiNG/assets/83868338/9a051bf6-2513-481f-811b-d14b6f806831)

As for a way to solve this, I suggest adding an alternative style of tracker status column (something like tracker message) that returns the error, if there is one, and when there isn't - the tracker message is returned. Or the current tracker status can be modified for this behavior, as I don't see any benefit to the current functionality.

**Comment by qu1ck** [comment]
Fixed in [v0.7.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v0.7.0)
