### ISSUE TITLE
Tidy up X buttons in pop up windows

### ISSUE THREAD

**Issue by Pentaphon** [openscopeproject/TrguiNG#48]
Here's what they look like on 0.7.0. It seems a bit off center, cutting off the button outline, making it tougher to click on a smaller screen. Can we get these more centered, and maybe a little bigger so they are easier to click? People might not have the same issue as I do, but as you can see from the screenshot, the X button could be tweaked a little to make it more centered, neat and more clickable. 

![corner](https://github.com/openscopeproject/TrguiNG/assets/49374058/de2c0c5d-edd2-49eb-85cf-5d3898d55415)

**Edit: also noticed this typo in the edit torrent properties window.**

![seess](https://github.com/openscopeproject/TrguiNG/assets/49374058/bb5646d9-e2f5-4a5c-9a10-8a504799bf27)

**Comment by qu1ck** [comment]
Fixed. FYI, don't feel compelled to aim for the X button, clicking anywhere outside of the dialog also closes it.

**Comment by qu1ck** [comment]
Fixed in [v0.8.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v0.8.0).
