### ISSUE TITLE
Several minor issues

### ISSUE THREAD

**Issue by username227** [openscopeproject/TrguiNG#5]
I'm very impressed with this new beta program. It looks new and fresh, and shows real promise. a few minor issues. For context, I'm using Arch and Cinnamon.

1) when the program is minimized to the tray, it still says "Hide" instead of "show" in the taskbar icon. In order to masximize the program, I need to first "hide" it even though it's already hidden and then show afterwards.

2) I tried adding a couple of torrents that I believe were already on the server, and it did not give me a message that they were already added. It seems like it was attempting to add it again.

**Comment by qu1ck** [comment]
1. Yes, noticed this too, only happens for "hide" and not "close" option.
2. You should get a notification of a duplicate if the torrent is already on the server
![image](https://github.com/openscopeproject/TrguiNG/assets/3622532/f1d08c5a-e791-4e55-afcf-0da02ce2e570)

If you don't see it check if the hashes match.

**Comment by qu1ck** [comment]
First issue should be fixed now.

**Comment by username227** [comment]
> First issue should be fixed now.

Thanks. Yes, I can confirm that the first issue is fixed.

I see what you mean about the message that the torrent is already present. However, I didn't notice it the first time because it seems to happen a lot later in the process of adding a torrent than in transgui and others. Namely, the message pops up after you've already set up the torrent that you're adding, chosen a path, and other options etc....I would imagine that the message that the torrent is already present would be more helpful if it popped up immediately and not so late in the process.

**Comment by qu1ck** [comment]
I agree, seeing that torrent is a duplicate before user spends time to setup download dir, files, etc. is useful.

Unlike Transgui (and probably other clients) TrguiNG doesn't send the torrent to transmission beforehand. There are some technical reasons for it: TrguiNG has ability to choose which server you add torrent to. Currently only by ctrl-tab/ctrl-shift-tab, it needs better visibility. 

So TrguiNG doesn't get a response from transmission until torrent is actually added. But It's still possible to show that torrent already exists in currently active tab by comparing hashes, I'll add that.

**Comment by qu1ck** [comment]
Ok, the message that torrent exists is showed ahead of time now. It doesn't allow to add the torrent anyway and update the tracker list like Transgui does but I have never found that feature useful. 

If you need it please file another issue, I'll look into it after v1 is released.
