### ISSUE TITLE
Request - in [Torrent context menu] rename "Remove" to "Delete" and add "Remove" option 

### ISSUE THREAD

**Issue by brutus-downunder** [openscopeproject/TrguiNG#64]
Hi,
There are times when you may want to remove a Torrent from downloads but not delete the actual file(s) (transmission-remote-gui).

My request would be to change the current [Torrent context menu]
1/ Rename "Remove" to "Delete"
2/ Add a "Remove" option which removes the Torrent from the downloading queue but without deleting the associated file(s)

Thanks.

**Comment by qu1ck** [comment]
Remove and delete operations are combined into single "remove" dialog which has an option to delete the files. It is also named appropriately because in both cases torrent is removed.

**Comment by Pentaphon** [comment]
I feel like this would just overcomplicate things. The current solution is simple and aligns with the original client.

**Comment by brutus-downunder** [comment]
Apologies for wasting your time.
I have rechecked the Remove dialog and it functions as you advised.
