### ISSUE TITLE
Unable to display any torrents

### ISSUE THREAD

**Issue by LordZZT** [openscopeproject/TrguiNG#65]
Howdy,

I normally use transmission-remote-gui, I have over 14,000 torrents and it works but is slow.
I noticed in trguiNG it is unable to display any torrents.
I took a quick look around, but couldn't find any logs to try and illustrate this.
![Screenshot_20230906_212736](https://github.com/openscopeproject/TrguiNG/assets/3058885/9eb427fd-6ecc-4397-a3d2-c20d1a271351)

**Comment by qu1ck** [comment]
I suspect with that many torrents the transmission is slow to build the response on server side and requests time out. You can open developer tools by right clicking a non-interactive element and selecting `inspect`. Then check if there are any errors in the console.

**Comment by LordZZT** [comment]
I'm using the linux app, however the normal transmission webUI does not have this problem, and is actually much faster than transmission-remote-gui. I fear the reason trguiNG is having an issue is the same reason transmission-remote-gui does which is to pull back all the data in one large request instead of paging it out

**Comment by qu1ck** [comment]
Transmission API does not have paging. You can disable unneeded columns to reduce amount of data the app will pull. But generally this APP is relatively heavy on data because it has much more functionality.

Did you check the devtools? Linux app has it too. If you can confirm that the issue is that the api requests are timing out then there are several things I could do to mitigate it.

**Comment by LordZZT** [comment]
I'm floored that transmission's API can't page.
I would've bet money on it as I remember reading that in one of their patch notes.
You are 100% correct, and after fumbling around I found the inspect option so that I can monitor it in the future.
Currently things are working as intended, So I assume it was just under high load.

**Comment by qu1ck** [comment]
It's possible to emulate paging by first getting a list of torrent ids and in subsequent requests get data for those ids in chunks. It would help with timeouts but would not speed up the app. More effective solution would be to get rid of some data heavy fields at the expense of some functionality (as a configurable option).

How does the app feel now? Is it responsive?
