### ISSUE TITLE
Options to skip confirmation dialogue and disable sound notification

### ISSUE THREAD

**Issue by argh0815** [openscopeproject/TrguiNG#66]
Truly awesome program, two options would make it even better (for me):
- Option to skip confirmation dialogue when adding a torrent by e.g. clicking on a magnet link.
- Option to not play a sound for download complete notification. I tried to change the Win 10 notification setting for the app but the sound is still being played.

**Comment by qu1ck** [comment]
Implemented in [v0.9.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v0.9.0)
