### ISSUE TITLE
Tracker list broken in versions of transmission <4

### ISSUE THREAD

**Issue by tml** [openscopeproject/TrguiNG#67]
When viewing a torrent's properties, if the version of transmission is less than version 4, the "tracker list" dialog is broken; on Transmission 3, it simply shows the number `0`.

![image](https://github.com/openscopeproject/TrguiNG/assets/35148/b6f5d10a-a08e-4510-adea-af58135775c0)

**Comment by jfeilbach** [comment]
It displays correctly on version 4.0.3 and 4.0.4 of transmission-daemon for me. I get a 0 on version 3.00. On version 2.94 it is blank.

**Comment by qu1ck** [comment]
Fixed in [v0.9.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v0.9.0)
