### ISSUE TITLE
Dark mode not preserved after restart

### ISSUE THREAD

**Issue by jfeilbach** [openscopeproject/TrguiNG#68]
On macOS when changed to dark mode, then exit and restart the the.app the dark mode setting is not preserved. This occurs on macOS version 13.5.2, macOS version 12.6.8, macOS Sonoma 14 Beta 7.

**Comment by qu1ck** [comment]
Weird. Do other settings get saved like server connections?
Which version of TrguiNG?

**Comment by tml** [comment]
Yes, other settings appear to be preserved. Confirmed using release "Swabbing the deck".

**Comment by jfeilbach** [comment]
I'm on version v0.8.1 All other settings seem to be retained.

**Comment by qu1ck** [comment]
I can not reproduce on MacOS 12.6.

Can you check what does "theme" in "interface" section of the config file say?
It is located in `/Users/your user/Library/Application Support/trguing.json`

**Comment by jfeilbach** [comment]
I do not have a "theme" key or value anywhere in` ~/Library/Application Support/trguing.json`. I restarted the app after setting dark mode, several times. Still nothing. I set it to light mode, then exited and now have `"theme": "light",` in the .json file.

**Comment by qu1ck** [comment]
Settings are saved every time the main window is closed (not hidden). It doesn't check if there are any changes, it should save current state every time. I am not sure why it wouldn't write the theme key for you. Kind of sounds like the app was crashing before it was able to save the file. Do you have anything in system crash reports?

**Comment by jfeilbach** [comment]
Yes there was an app crash as a result of my local firewall blocking a new server being added. I searched through console logs and found not find anything for string `trguing` or `TrguiNG` Sorry.

**Comment by qu1ck** [comment]
Since this was reported a few fixes for crashes were done and are in [v1.0.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v1.0.0)

If this issue still exists please reopen.

**Comment by ruizlenato** [comment]
the problem persists

https://github.com/openscopeproject/TrguiNG/assets/49354525/be86eb80-a032-4086-809b-736db6784418

**Comment by qu1ck** [comment]
You are running into this issue https://github.com/openscopeproject/TrguiNG/discussions/177 it's similar but different.

The fix is already in, until next version is released you can use the theme icon in the bottom right corner, that one is saved.
