### ISSUE TITLE
Arrow keys don’t do what’s expected

### ISSUE THREAD

**Issue by nicknlsn** [openscopeproject/TrguiNG#69]
Up and down arrow keys scroll the view but it only works for a few keystrokes, then doesn't do anything. Also, I think it would make more sense if the arrow keys changed which torrent is select instead of scrolling the view. It would also be nice if the shift key worked to select multiple torrents at once.

**Comment by jfeilbach** [comment]
shift+arrow keys fails. select then shift + moving mouse cursor works.

**Comment by qu1ck** [comment]
Shift + mouse click and also ctrl + mouse click works for multiple selections.

For arrow keys to switch torrents see #46.
