### ISSUE TITLE
Feature request: Even more powerful filtering options

### ISSUE THREAD

**Issue by mahkitah** [openscopeproject/TrguiNG#7]
This looks like a promising project that has the potential to replace RemoteGui and Tremotesf.
But I'm a bit bit underwhelmed by the 'Powerful filtering options'.

The lack of a Trackers section is a deal breaker for me.

And there are two features from tremotesf that would be really nice to have:
- Combine filter sections (e.g. see all Active torrents from directory x)
- Enable/Disable a whole section

**Comment by qu1ck** [comment]
Tracker filtering and options to hide filter sections will be added soon.

Can you expand on combined filters? How exactly does the UI work?

**Comment by mahkitah** [comment]
Good to hear tracker filtering is coming.

Combined filters:
Make a selection based on multiple filter sections.
At the moment when you select something from one section, the selection from another section disappears.
In tremotesf that doesn't happen. You can select options from multiple sections simultaneously.
(within a section there's still only one option possible)

Does that make things clearer?

**Comment by mahkitah** [comment]
The way it is in tremotesf:
No ctrl-click, just normal clicking but the sections just work independently.
Only AND logic.

Off course you can do things differently.
OR logic (+ ctrl-click) would make sense within a section: Show torrents in dir x OR y AND from tracker a OR b

**Comment by qu1ck** [comment]
Got it, thank you. 

For now I'm thinking simple AND logic but not limited to different sections. More complex logic can be considered after v1 release.

**Comment by qu1ck** [comment]
You can now ctrl-click multiple filters to combine them (even across different sections).

**Comment by qu1ck** [comment]
Actually, I'll close this when fixes are released. If you compile yourself you can try them early.

**Comment by username227** [comment]
I actually came on just to request this: filter by tracker.

**Comment by qu1ck** [comment]
Implemented in [v0.3.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v0.3.0).
