### ISSUE TITLE
Multi tracker edit

### ISSUE THREAD

**Issue by nicknlsn** [openscopeproject/TrguiNG#76]
Feature request: ability to bulk edit trackers.

**Comment by jfeilbach** [comment]
Selecting multiple torrents then go to properties. It is unavailable. This worked in transgui. Would be nice to have this feature for bulk editing trackers on multiple torrents simultaneously.

**Comment by qu1ck** [comment]
#57 is related. There are issues with batch editing torrents like that, it's easy to break private torrents.
I think splitting the tracker list out of properties would mitigate most of the risk here.

**Comment by qu1ck** [comment]
Trackers are now edited in a separate dialog to minimize chance of breaking torrents.
You can now edit properties of multiple torrents. Editing trackers of multiple torrents also works but only for transmission server v4.0 or later.

**Comment by qu1ck** [comment]
Implemented in [v0.10.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v0.10.0).
