### ISSUE TITLE
TrguiNG cannot open files in the "BitTorrent Document" format

### ISSUE THREAD

**Issue by rflois** [openscopeproject/TrguiNG#79]
I get this error when trying to open any torrent files from the Finder on my Mac. TrguiNG is set as the default for opening .torrent files. If I try to open them from within TrguiNG, they work without issue.

I'm running version 0.8.1-3-g1c0d926.

<img width="372" alt="Screenshot 2023-09-13 at 16 42 43" src="https://github.com/openscopeproject/TrguiNG/assets/1617009/9d32f105-3753-4245-86b9-a5bf0257b2cd">

**Comment by qu1ck** [comment]
Judging by the version you have compiled the app yourself. In that case you need to copy the full release bundle into `Applications` and run it from there once so that the OS associates the manifest to the app and learns about the supported file types.

**Comment by rflois** [comment]
Strange. Manually opening it from /Applications worked, even though I had copied it there weeks ago and had been running it ever since, but likely opening it from the Dock. Anyways, all good here. Thanks!

**Comment by wally-crunk** [comment]
Hi, this issue was still happening (2024) for me.  
• I downloaded the pre-compiled version, so that's not a factor.

This message occurs when:
• I open the .torrent file by double-clicking from the Finder,
• I open the .torrent file by right-clicking and using Open With...
This message does NOT cocur when:
• I open the .torrent file(s) by dragging into the window.

Dragging the application out of the Applications folder and back in again does not solve it.
**Deleting the application and reinstalling from the latest .tar.gz file seems to have solved it for now.**

**Comment by wally-crunk** [comment]
Negative, not solved for me: if you install a different torrent app (like qBittorrent), the message returns, even if you delete that app.

Any ideas?

**Comment by qu1ck** [comment]
I can not reproduce.
After reinstalling the app did you try opening it from `/Applications` for first time?

**Comment by wally-crunk** [comment]
> After reinstalling the app did you try opening it from `/Applications` for first time?

Yes, I continue to get this error, even after reinstalling the app, deleting other Torrent apps, and launching the "new" TrguiNG.app from the Applications fold

<img width="172" alt="screenshot" src="https://github.com/user-attachments/assets/226130d8-a898-443f-a0b5-bfe509259d9e" />
er _before_ double clicking any .torrent files.

**Comment by qu1ck** [comment]
Well I still can't reproduce, right away or months later, the app opens torrent files fine for me.
Try to pinpoint what is causing the app to stop opening files at a later date, possible causes are OS update, system reboot, system backup restore, installing other apps that open torrent files. It sounds like something on your system is changing if the app works at first and then stops.

I am not a macos dev so it's possible that I messed up something in the manifest and Macos does not properly associate the app with torrent files but if that was the case then it shouldn't work and then stop, it just wouldn't work in the first place. So I'm at a loss here.
