### ISSUE TITLE
Right-click does not select

### ISSUE THREAD

**Issue by mahkitah** [openscopeproject/TrguiNG#8]
In the main table when you right-click a torrent, it does not select that torrent.
This is annoying when there's no torrent selected yet because you have to left-click first and then right-click.
But it does really lead to unexpected results when a torrent is selected and you right click on a different one; the context actions will affect the selected torrent even though you clicked a different one.

**Comment by qu1ck** [comment]
Fixed in [v0.3.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v0.3.0).
