### ISSUE TITLE
Icons for common file extensions on the WebUI? 

### ISSUE THREAD

**Issue by Pentaphon** [openscopeproject/TrguiNG#81]
Can we have icons for general filetypes on the WebUI? Like a video icon for mp4 or mkv? Music icon for FLAC or mp3?

It would be nice to have icons for each filetype but that's probably asking for too much.

**Comment by qu1ck** [comment]
Implemented in [v0.9.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v0.9.0)
