### ISSUE TITLE
Path mapping issue: colons in name are actually underscores

### ISSUE THREAD

**Issue by elboletaire** [openscopeproject/TrguiNG#85]
I cannot open a torrent with the following name:

    Malevolent Spirits: Mononogatari S02 1080p Subsplease -END

Checking my downloads dir, the path is actually `Malevolent Spirits_ Mononogatari S02 1080p Subsplease -END` (only changes the colon by an underscore), which makes sense considering some systems (Windows more precisely) don't allow the colon into filenames.

There are probably other symbols that are converted by transmission, so it's probably a good idea to add all of them.

**Comment by qu1ck** [comment]
What is your OS and your transmission server OS? Do you use Samba/CIFS share?

I suspect this is not something TrguiNG can fix because it's server side settings dependent.

**Comment by elboletaire** [comment]
Oops, sorry, it was late and I totally forgot to give you more details.

The server is arch linux, the files are served via samba, but the linux filesystem shows it as `_` too, so I don't think it's samba related, but transmission daemon related (some conversion it does behind the scenes).

The client using the transmission remote uses Windows 11:
![imatge](https://github.com/openscopeproject/TrguiNG/assets/153305/9fdd4d36-ceb7-437a-bd52-863ca5160f65)

**Comment by qu1ck** [comment]
Hm. I tried to rename an existing torrent to include a colon and transmission let me do it, the folder on linux FS also had the colon. Samba in my case straight up does not show that folder but it depends on samba config, which is why I posted the above.

I will test if transmission does the conversion when torrent is added. If it does then maybe I'm using wrong field to determine the path (I thought the name is always the same as the path so used that).

**Comment by qu1ck** [comment]
Transgui is not at fault here, it's the way torrent file itself was created.

> But if you do such conversion, won't it fail for people having a colon in the name?

Yes. I'll have to disable ability to rename torrent or files within to a name with illegal characters (even if they are not illegal on their os). Then if you already have torrents renamed that way... you'll have to go back to a previous version to rename them back. 

But to end up in that state would require you manually naming files with special chars and it's always a bad idea to have special chars in file paths so... I think it's justified :D

Doing it this way will also fix the related bug that you currently can not rename torrent that has a colon in it at all.

**Comment by elboletaire** [comment]
I do now realize the file isn't even properly moved to the completed download files, and found this, which is probably the root issue https://github.com/transmission/transmission/issues/1700

**Comment by qu1ck** [comment]
The root issue are out of spec torrent files, you can expect all kinds of undefined behavior with them.

For what it's worth if you don't use separate dir for incomplete torrents transmission handles them fine.

**Comment by qu1ck** [comment]
Fixed as much as it can be in [v0.10.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v0.10.0).
