### ISSUE TITLE
Feature Request: Sort alphabeticly after sorting by status or etc.

### ISSUE THREAD

**Issue by Dlanis** [openscopeproject/TrguiNG#87]
I like to sort by status to quickly see what torrents are downloading and etc, but without the feature list is pretty mess.

**Comment by jfeilbach** [comment]
I think this is already in place. After selecting the status you want, click on the column header you want to sort by, in your case, status.

**Comment by qu1ck** [comment]
You are asking for multi column sort.
It's possible but making a good UI for it is a pain in the behind. How do you differentiate primary and secondary sort? How do you control secondary sort direction without changing primary sort? How do you reset sort? A lot of cases here that don't work easily unless you build separate explicit controls for sorting. I like the current click header to sort so not too keen on changing that.

What you want is achievable with filters on the left, use them. Keep your column sorted by date/name/whatever and click status filters to quickly see what's downloading etc.

**Comment by Dlanis** [comment]
Oh. I have just noticed that if shift click on column name it will be selected as secondary sort. I think that should be documented.

**Comment by qu1ck** [comment]
Yeah, that works but it's not good UI, partly because it's not intuitive and has to be documented.
