### ISSUE TITLE
Allow F2 key to enter name editing mode of the selected torrent

### ISSUE THREAD

**Issue by wikiped** [openscopeproject/TrguiNG#88]
An item to the wishlist

**Comment by qu1ck** [comment]
> And allow to change the name when adding a torrent, not just after the fact.

This will not be implemented, it's not supported by transmission API. Original transmission remote gui has a hacky workaround that is not feasible in TrguiNG.

**Comment by Beersteddy** [comment]
Option to rename torrents it's very important for an app like this.
It will be very handy to have it

**Comment by qu1ck** [comment]
You can rename torrents, it is just not mapped to a hotkey right now. When you hover over the name of the torrent in the table a rename button appears inline.

**Comment by Beersteddy** [comment]
> You can rename torrents, it is just not mapped to a hotkey right now. When you hover over the name of the torrent in the table a rename button appears inline.

Ha.
Totally missed it. I was hunting for it in the right-click pop-up menu

Good to know, although still think that F2 is vital


For other `spotters` like me:

![image](https://github.com/openscopeproject/TrguiNG/assets/91010735/3668211b-d1a5-40ba-b2cf-667264298de6)

**Comment by qu1ck** [comment]
Implemented in [v1.0.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v1.0.0)
