### ISSUE TITLE
Can't add Ubuntu torrent with torrent file uploader but can add it via http link

### ISSUE THREAD

**Issue by Pentaphon** [openscopeproject/TrguiNG#9]
Not sure if this is reproducible but it happened to me. Latest Firefox on Windows 11 using Transmission-daemon 4.0.3

Admittedly, this torrent is known to connect slowly with Transmission as per https://github.com/transmission/transmission/discussions/4916 but it never fails to add to the Qt or GTK client. Also, I tried TransGUI and tremotesf and it adds just fine there too. 

https://releases.ubuntu.com/23.04/ubuntu-23.04-desktop-amd64.iso.torrent

1) Try downloading this torrent file to your PC and then use the torrent file uploader. It simply won't add. The add torrent prompt won't even come up. 
2) Now just paste the link into the add link function and the torrent will add just fine. The add torrent prompt comes up. No issue at all. 

Very strange. Not sure why it wouldn't just work. 

I've tried this with other public torrents like the popular MX Linux torrent: https://l2.mxrepo.com/torrents/MX-21.3_x64.iso.torrent and there's no issues with it whatsoever. Just the Ubuntu torrent seems to have issues.

**Comment by qu1ck** [comment]
There was a bug with large torrent files, fixed now.

**Comment by qu1ck** [comment]
Fixed in [v0.3.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v0.3.0).
