### ISSUE TITLE
Feature request: "open file location" for single file torrents

### ISSUE THREAD

**Issue by elboletaire** [openscopeproject/TrguiNG#92]
With single-file torrents, having an `open file location` option in the context menu would be awesome.

Edit: and/or add the "open" feature in the sidebar "directories" tree list (maybe more `and` than `or`, since it's not the same feature, and does not work as an alternative for the `open file location`, unless you're already filtering that directory).

**Comment by qu1ck** [comment]
Implemented in [v0.10.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v0.10.0).
