### ISSUE TITLE
labels doesn't work

### ISSUE THREAD

**Issue by simonbcn** [openscopeproject/TrguiNG#95]
Client:
```
macOS 14
TrguiNG v0.9.0 (TrguiNG_aarch64.app.tar.gz)
```
Server:
```
Linux NixOS 23.05
Transmission v3.00
```

This is a screenshot of the TrguiNG window adding a torrent file:
![Captura de pantalla 2023-10-17 a las 13 28 31](https://github.com/openscopeproject/TrguiNG/assets/428231/f46a69b6-4860-4639-802b-62a300fd80f8)

It does not allow me to add any labels to the torrent I am trying to add. I also can't find any way in the application to create/manage the tags.

**Comment by qu1ck** [comment]
Can you show the bottom of the window? It shows server version there, 3.00 supports labels so they should be available.

**Comment by simonbcn** [comment]
![Captura de pantalla 2023-10-17 a las 13 38 09](https://github.com/openscopeproject/TrguiNG/assets/428231/26467edb-4e3e-4d54-a268-6db3c1b37c87)

**Comment by qu1ck** [comment]
Ah, right, specifying labels when adding a torrent is supported in transmission 4.0 and later. But you can edit labels of already added torrents, select them and press F7 or right click torrent and select "Set labels..." or click the blue tags icon on the toolbar.
