### ISSUE TITLE
Clicking the files tab turns the app into a blank white screen

### ISSUE THREAD

**Issue by nicknlsn** [openscopeproject/TrguiNG#99]
I believe this is a javascript issue. It looks like it prints an error for every file in the torrent, i.e. for a one file torrent it prints the error once. This screenshot is from a season pack. I'm on transmission 3.

<img width="1680" alt="Screen Shot" src="https://github.com/openscopeproject/TrguiNG/assets/6007603/0295ccc5-cce2-4de0-a8ec-2763343c4305">

**Comment by qu1ck** [comment]
Can you post screenshot from the version info window? Click the "i" icon in top right.

**Comment by nicknlsn** [comment]
<img width="453" alt="Screen Sho" src="https://github.com/openscopeproject/TrguiNG/assets/6007603/9c302494-3edf-4d08-ac99-9759bf993707">

**Comment by qu1ck** [comment]
Strange, I have the same reported webkit version but it works for me. Do you have os updates installed, specifically safari?
What is your OS version and safari version?

**Comment by nicknlsn** [comment]
Safari: Version 16.6.1 (16615.3.12.11.5, 16615)
macOS: 11.7.10 (20G1427)

I'm on an older Mac, it's a retina 13-inch from late 2013. Software updater says I'm up to date.

**Comment by qu1ck** [comment]
That's still supported and should be up to date but looks like apple is lazy about updating system webview libs.

Anyway, I pushed a fix for this particular issue. If you can compile yourself, pull the latest, otherwise it will be in next version.

**Comment by nicknlsn** [comment]
Awesome! Thank you.

**Comment by nicknlsn** [comment]
The new build fixes the issue. Thanks again, love the app.

**Comment by qu1ck** [comment]
Fixed in [v0.10.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v0.10.0).
